/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-05-31 05:04:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class inbox_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--------------------------------------------------------------------\r\n");
      out.write("----------------------------------------------------------------------\r\n");
      out.write("\r\n");
      out.write("                        Manobandhan Inbox Page\r\n");
      out.write("            \r\n");
      out.write("-----------------------------------------------------------------------\r\n");
      out.write("----------------------------------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("  \r\n");
      out.write("  <title>Manobandhan</title>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"images/logo/Mano1.png\" type=\"image/x-icon\" />    \r\n");
      out.write("    <link href=\"css/temp.css\" rel=\"stylesheet\" type=\"text/css\"/>    \r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/home.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/font-awesome.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/bootstrap-3.1.1.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\"/>    \r\n");
      out.write("        <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"js/jquery.flexisel.js\"></script>\r\n");
      out.write("        <script src=\"js/bootstrap.min.js\"></script> \r\n");
      out.write("        <script src=\"js/login1.js\"></script>      \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write(".banner {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  \r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write(" \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".banner img {vertical-align: middle;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".banner .content {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  background: rgb(0, 0, 0); /* Fallback color */\r\n");
      out.write("  background: rgba(0, 0, 0, 0.5); /* Black background with 0.5 opacity */\r\n");
      out.write("  color: #f1f1f1;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  margin-bottom: 68px;\r\n");
      out.write("}\r\n");
      out.write(".profile-picture {\r\n");
      out.write("\tborder-radius: 100%;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\t-webkit-box-sizing: content-box;\r\n");
      out.write("  \t-moz-box-sizing: content-box;\r\n");
      out.write("  \tbox-sizing: content-box;\t\r\n");
      out.write("}\r\n");
      out.write("\t.small-profile-picture {\r\n");
      out.write("\t\tborder: 2px solid #50597b;\r\n");
      out.write("\t\twidth: 40px;\r\n");
      out.write("\t\theight: 40px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.big-profile-picture {\r\n");
      out.write("\t\tmargin: 0 auto;\t\t\r\n");
      out.write("\t\tborder: 5px solid #50597b;\r\n");
      out.write("\t\twidth: 150px;\r\n");
      out.write("\t\theight: 150px;\r\n");
      out.write("        \r\n");
      out.write("\t}\r\n");
      out.write("    \r\n");
      out.write(".nav-tabs > li > a, \r\n");
      out.write(".nav-tabs > li > a:hover, \r\n");
      out.write(".nav-tabs > li > a:focus, \r\n");
      out.write(".nav-tabs > li.active > a, \r\n");
      out.write(".nav-tabs > li.active > a:hover,\r\n");
      out.write(".nav-tabs > li.active > a:focus {\r\n");
      out.write("  border: none;\r\n");
      out.write("  border-radius: 0;\r\n");
      out.write("  background-color:#ffa417;\r\n");
      out.write("}    \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<!---------------------header,Menu----------------------------------------------------------->\r\n");
      out.write("    \r\n");
      out.write("<!---------------------------Content mid------------------------------------------------------->\r\n");
      out.write("               \r\n");
      out.write("<div class=\"grid_3\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("   <div class=\"breadcrumb1\">\r\n");
      out.write("     <ul>\r\n");
      out.write("        <a href=\"profile.jsp\"><i class=\"fa fa-home home_1\"></i></a>\r\n");
      out.write("        <span class=\"divider\">&nbsp;|&nbsp;</span>\r\n");
      out.write("        <li class=\"current-page\"><h3>Inbox</h3></li>\r\n");
      out.write("     </ul>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"col-md-3 col_5\">\r\n");
      out.write("   \t <ul class=\"match_box\">\r\n");
      out.write("   \t \t<h4>Matches</h4>\r\n");
      out.write("   \t \t<li><a href=\"#\">Mutual Matches</a></li>\r\n");
      out.write("   \t \t<li><a href=\"#\">Profiles yet to be viewed</a></li>\r\n");
      out.write("   \t \t<li><a href=\"#\">Mutual Matches</a></li>\r\n");
      out.write("   \t </ul>\r\n");
      out.write("   \t <img src=\"images/v1.jpg\" class=\"img-responsive\" alt=\"\"/>\r\n");
      out.write("     <ul class=\"menu\">\r\n");
      out.write("\t\t<li class=\"item1\"><h3 class=\"m_2\">Show Profiles Created</h3>\r\n");
      out.write("\t\t  <ul class=\"cute\">\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">within a week (2) </a></li>\r\n");
      out.write("\t\t\t<li class=\"subitem2\"><a href=\"#\">within a month (4)</a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"item1\"><h3 class=\"m_2\">Profile type</h3>\r\n");
      out.write("\t\t  <ul class=\"cute\">\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">with Photo (3) </a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"item1\"><h3 class=\"m_2\">Marital Status</h3>\r\n");
      out.write("\t\t  <ul class=\"cute\">\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Unmarried (2) </a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"item1\"><h3 class=\"m_2\">Mother Tongue</h3>\r\n");
      out.write("\t\t  <ul class=\"cute\">\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">English </a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"item1\"><h3 class=\"m_2\">Education</h3>\r\n");
      out.write("\t\t  <ul class=\"cute\">\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Bachelors-Engineering </a></li>\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Masters-Engineering </a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"item1\"><h3 class=\"m_2\">Occupation</h3>\r\n");
      out.write("\t\t  <ul class=\"cute\">\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Engineer-Non IT (2) </a></li>\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Software Professional (3)</a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"item1\"><h3 class=\"m_2\">Physical Status</h3>\r\n");
      out.write("\t\t  <ul class=\"cute\">\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Normal (2) </a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"item1\"><h3 class=\"m_2\">Eating Habits</h3>\r\n");
      out.write("\t\t  <ul class=\"cute\">\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Non Vegetarian (3)</a></li>\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Vegetarian (2)</a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"item1\"><h3 class=\"m_2\">Smoking</h3>\r\n");
      out.write("\t\t  <ul class=\"cute\">\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Not Specified (3)</a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"item1\"><h3 class=\"m_2\">Drinking</h3>\r\n");
      out.write("\t\t  <ul class=\"cute\">\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Not Specified (3)</a></li>\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Never Drinks (3)</a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"item1\"><h3 class=\"m_2\">Profile Created by</h3>\r\n");
      out.write("\t\t  <ul class=\"cute\">\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Self (1)</a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t  </ul>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"col-md-9 members_box2\">\r\n");
      out.write("   \t   <h3>Inbox</h3>\r\n");
      out.write("   \t   <p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \"de Finibus Bonorum et Malorum\" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>\r\n");
      out.write("       <div class=\"col_4\">\r\n");
      out.write("\t\t    <div class=\"bs-example bs-example-tabs\" role=\"tabpanel\" data-example-id=\"togglable-tabs\">\r\n");
      out.write("\t\t\t   <ul id=\"myTab\" class=\"nav nav-tabs nav-tabs1\" role=\"tablist\">\r\n");
      out.write("\t\t\t\t  <li role=\"presentation\" class=\"active\"><a href=\"#home\" id=\"home-tab\" role=\"tab\" data-toggle=\"tab\" aria-controls=\"home\" aria-expanded=\"true\">All</a></li>                 \r\n");
      out.write("                  <li role=\"presentation\"><a href=\"#profile\" role=\"tab\" id=\"profile-tab\" data-toggle=\"tab\" aria-controls=\"profile\">New</a></li>\r\n");
      out.write("\t\t\t\t  <li role=\"presentation\"><a href=\"#profile1\" role=\"tab\" id=\"profile-tab\" data-toggle=\"tab\" aria-controls=\"profile\">Read</a></li>\r\n");
      out.write("\t\t\t\t  <li role=\"presentation\"><a href=\"#profile2\" role=\"tab\" id=\"profile-tab\" data-toggle=\"tab\" aria-controls=\"profile\">Accepted</a></li>\r\n");
      out.write("\t\t\t\t  <li role=\"presentation\"><a href=\"#profile2\" role=\"tab\" id=\"profile-tab\" data-toggle=\"tab\" aria-controls=\"profile\">Not Interested</a></li>\r\n");
      out.write("\t\t\t   </ul>\r\n");
      out.write("\t\t\t   <div id=\"myTabContent\" class=\"tab-content\">\r\n");
      out.write("\t\t\t\t  <div role=\"tabpanel\" class=\"tab-pane fade in active\" id=\"home\" aria-labelledby=\"home-tab\">\r\n");
      out.write("\t\t\t\t    <ul class=\"pagination pagination_1\">\r\n");
      out.write("\t\t\t\t \t  <li class=\"active\"><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t\t\t \t  <li><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t\t\t \t  <li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t\t\t \t  <li><a href=\"#\">4</a></li>\r\n");
      out.write("\t\t\t\t \t  <li><a href=\"#\">5</a></li>\r\n");
      out.write("\t\t\t\t \t  <li><a href=\"#\">...</a></li>\r\n");
      out.write("\t\t\t\t \t  <li><a href=\"#\">Next</a></li>\r\n");
      out.write("\t                </ul>\r\n");
      out.write("\t                <div class=\"clearfix\"> </div>\r\n");
      out.write("\t                <div class=\"jobs-item with-thumb\">\r\n");
      out.write("\t                   <div class=\"thumb_top\">\r\n");
      out.write("\t\t\t\t        <div class=\"thumb\"><a href=\"view_profile.html\"><img src=\"images/p13.jpg\" class=\"img-responsive\" alt=\"\"/></a></div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"jobs_right\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"title\"><a href=\"view_profile.html\">Lorem (2547189)</a></h6>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"top-btns\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-facebook\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-twitter\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-google-plus\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"login_details1\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li>Last Login : 5 days ago</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"description\">30 years, 5 Ft 7 In / 170 Cms | <span class=\"m_1\">Reliogion</span> : Hindu | <span class=\"m_1\">Education</span> : B.Tech | <span class=\"m_1\">Occupation</span> : Software Professional<br><a href=\"view_profile.html\" class=\"read-more\">view full profile</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t   <div class=\"thumb_bottom\">\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"thumb\"><a href=\"view_profile.html\" class=\"photo_view\">Add Photo</a></div>\r\n");
      out.write("\t\t\t\t\t   \t   <div class=\"thumb_but\"><a href=\"view_profile.html\" class=\"photo_view\">Send Mail</a></div>\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"jobs-item with-thumb\">\r\n");
      out.write("\t                   <div class=\"thumb_top\">\r\n");
      out.write("\t\t\t\t        <div class=\"thumb\"><a href=\"view_profile.html\"><img src=\"images/p15.jpg\" class=\"img-responsive\" alt=\"\"/></a></div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"jobs_right\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"title\"><a href=\"view_profile.html\">Lorem (2547189)</a></h6>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"top-btns\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-facebook\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-twitter\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-google-plus\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"login_details1\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li>Last Login : 5 days ago</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"description\">30 years, 5 Ft 7 In / 170 Cms | <span class=\"m_1\">Reliogion</span> : Hindu | <span class=\"m_1\">Education</span> : B.Tech | <span class=\"m_1\">Occupation</span> : Software Professional<br><a href=\"view_profile.html\" class=\"read-more\">view full profile</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t   <div class=\"thumb_bottom\">\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"thumb\"><a href=\"view_profile.html\" class=\"photo_view\">Add Photo</a></div>\r\n");
      out.write("\t\t\t\t\t   \t   <div class=\"thumb_but\"><a href=\"view_profile.html\" class=\"photo_view\">Send Mail</a></div>\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"jobs-item with-thumb\">\r\n");
      out.write("\t                   <div class=\"thumb_top\">\r\n");
      out.write("\t\t\t\t        <div class=\"thumb\"><a href=\"view_profile.html\"><img src=\"images/p14.jpg\" class=\"img-responsive\" alt=\"\"/></a></div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"jobs_right\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"title\"><a href=\"view_profile.html\">Lorem (2547189)</a></h6>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"top-btns\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-facebook\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-twitter\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-google-plus\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"login_details1\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li>Last Login : 5 days ago</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"description\">30 years, 5 Ft 7 In / 170 Cms | <span class=\"m_1\">Reliogion</span> : Hindu | <span class=\"m_1\">Education</span> : B.Tech | <span class=\"m_1\">Occupation</span> : Software Professional<br><a href=\"view_profile.html\" class=\"read-more\">view full profile</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t   <div class=\"thumb_bottom\">\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"thumb\"><a href=\"view_profile.html\" class=\"photo_view\">Add Photo</a></div>\r\n");
      out.write("\t\t\t\t\t   \t   <div class=\"thumb_but\"><a href=\"view_profile.html\" class=\"photo_view\">Send Mail</a></div>\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"jobs-item with-thumb\">\r\n");
      out.write("\t                   <div class=\"thumb_top\">\r\n");
      out.write("\t\t\t\t        <div class=\"thumb\"><a href=\"view_profile.html\"><img src=\"images/p16.jpg\" class=\"img-responsive\" alt=\"\"/></a></div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"jobs_right\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"title\"><a href=\"view_profile.html\">Lorem (2547189)</a></h6>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"top-btns\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-facebook\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-twitter\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-google-plus\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"login_details1\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li>Last Login : 5 days ago</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"description\">30 years, 5 Ft 7 In / 170 Cms | <span class=\"m_1\">Reliogion</span> : Hindu | <span class=\"m_1\">Education</span> : B.Tech | <span class=\"m_1\">Occupation</span> : Software Professional<br><a href=\"view_profile.html\" class=\"read-more\">view full profile</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t   <div class=\"thumb_bottom\">\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"thumb\"><a href=\"view_profile.html\" class=\"photo_view\">Add Photo</a></div>\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"thumb_but\"><a href=\"view_profile.html\" class=\"photo_view\">Send Mail</a></div>\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"jobs-item with-thumb\">\r\n");
      out.write("\t                   <div class=\"thumb_top\">\r\n");
      out.write("\t\t\t\t        <div class=\"thumb\"><a href=\"view_profile.html\"><img src=\"images/p17.jpg\" class=\"img-responsive\" alt=\"\"/></a></div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"jobs_right\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"title\"><a href=\"view_profile.html\">Lorem (2547189)</a></h6>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"top-btns\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-facebook\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-twitter\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-google-plus\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"login_details1\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li>Last Login : 5 days ago</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"description\">30 years, 5 Ft 7 In / 170 Cms | <span class=\"m_1\">Reliogion</span> : Hindu | <span class=\"m_1\">Education</span> : B.Tech | <span class=\"m_1\">Occupation</span> : Software Professional<br><a href=\"view_profile.html\" class=\"read-more\">view full profile</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t   <div class=\"thumb_bottom\">\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"thumb\"><a href=\"view_profile.html\" class=\"photo_view\">Add Photo</a></div>\r\n");
      out.write("\t\t\t\t\t   \t   <div class=\"thumb_but\"><a href=\"view_profile.html\" class=\"photo_view\">Send Mail</a></div>\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"jobs-item with-thumb\">\r\n");
      out.write("\t                   <div class=\"thumb_top\">\r\n");
      out.write("\t\t\t\t        <div class=\"thumb\"><a href=\"view_profile.html\"><img src=\"images/s3.jpg\" class=\"img-responsive\" alt=\"\"/></a></div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"jobs_right\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"title\"><a href=\"view_profile.html\">Lorem (2547189)</a></h6>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"top-btns\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-facebook\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-twitter\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-google-plus\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"login_details1\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li>Last Login : 5 days ago</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"description\">30 years, 5 Ft 7 In / 170 Cms | <span class=\"m_1\">Reliogion</span> : Hindu | <span class=\"m_1\">Education</span> : B.Tech | <span class=\"m_1\">Occupation</span> : Software Professional<br><a href=\"view_profile.html\" class=\"read-more\">view full profile</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t   <div class=\"thumb_bottom\">\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"thumb\"><a href=\"view_profile.html\" class=\"photo_view\">Add Photo</a></div>\r\n");
      out.write("\t\t\t\t\t   \t   <div class=\"thumb_but\"><a href=\"view_profile.html\" class=\"photo_view\">Send Mail</a></div>\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div role=\"tabpanel\" class=\"tab-pane fade\" id=\"profile\" aria-labelledby=\"profile-tab\">\r\n");
      out.write("\t\t\t\t    <div class=\"jobs-item with-thumb\">\r\n");
      out.write("\t                   <div class=\"thumb_top\">\r\n");
      out.write("\t\t\t\t        <div class=\"thumb\"><a href=\"view_profile.html\"><img src=\"images/s3.jpg\" class=\"img-responsive\" alt=\"\"/></a></div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"jobs_right\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"title\"><a href=\"view_profile.html\">Lorem (2547189)</a></h6>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"top-btns\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-facebook\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-twitter\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-google-plus\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"login_details1\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li>Last Login : 5 days ago</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"description\">30 years, 5 Ft 7 In / 170 Cms | <span class=\"m_1\">Reliogion</span> : Hindu | <span class=\"m_1\">Education</span> : B.Tech | <span class=\"m_1\">Occupation</span> : Software Professional<br><a href=\"view_profile.html\" class=\"read-more\">view full profile</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t   <div class=\"thumb_bottom\">\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"thumb\"><a href=\"view_profile.html\" class=\"photo_view\">Add Photo</a></div>\r\n");
      out.write("\t\t\t\t\t   \t   <div class=\"thumb_but\"><a href=\"view_profile.html\" class=\"photo_view\">Send Mail</a></div>\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"jobs-item with-thumb\">\r\n");
      out.write("\t                   <div class=\"thumb_top\">\r\n");
      out.write("\t\t\t\t        <div class=\"thumb\"><a href=\"view_profile.html\"><img src=\"images/s3.jpg\" class=\"img-responsive\" alt=\"\"/></a></div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"jobs_right\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"title\"><a href=\"view_profile.html\">Lorem (2547189)</a></h6>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"top-btns\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-facebook\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-twitter\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-google-plus\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"login_details1\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li>Last Login : 5 days ago</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"description\">30 years, 5 Ft 7 In / 170 Cms | <span class=\"m_1\">Reliogion</span> : Hindu | <span class=\"m_1\">Education</span> : B.Tech | <span class=\"m_1\">Occupation</span> : Software Professional<br><a href=\"view_profile.html\" class=\"read-more\">view full profile</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t   <div class=\"thumb_bottom\">\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"thumb\"><a href=\"view_profile.html\" class=\"photo_view\">Add Photo</a></div>\r\n");
      out.write("\t\t\t\t\t   \t   <div class=\"thumb_but\"><a href=\"view_profile.html\" class=\"photo_view\">Send Mail</a></div>\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"jobs-item with-thumb\">\r\n");
      out.write("\t                   <div class=\"thumb_top\">\r\n");
      out.write("\t\t\t\t        <div class=\"thumb\"><a href=\"view_profile.html\"><img src=\"images/s3.jpg\" class=\"img-responsive\" alt=\"\"/></a></div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"jobs_right\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"title\"><a href=\"view_profile.html\">Lorem (2547189)</a></h6>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"top-btns\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-facebook\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-twitter\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-google-plus\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"login_details1\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li>Last Login : 5 days ago</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"description\">30 years, 5 Ft 7 In / 170 Cms | <span class=\"m_1\">Reliogion</span> : Hindu | <span class=\"m_1\">Education</span> : B.Tech | <span class=\"m_1\">Occupation</span> : Software Professional<br><a href=\"view_profile.html\" class=\"read-more\">view full profile</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t   <div class=\"thumb_bottom\">\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"thumb\"><a href=\"view_profile.html\" class=\"photo_view\">Add Photo</a></div>\r\n");
      out.write("\t\t\t\t\t   \t   <div class=\"thumb_but\"><a href=\"view_profile.html\" class=\"photo_view\">Send Mail</a></div>\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t <div role=\"tabpanel\" class=\"tab-pane fade\" id=\"profile1\" aria-labelledby=\"profile-tab\">\r\n");
      out.write("\t\t\t\t    <div class=\"terms\">\r\n");
      out.write("            \t\t  <h2>Your Privacy Settings</h2>\r\n");
      out.write("\t\t\t\t\t   <div class=\"terms_top\">\r\n");
      out.write("\t\t\t\t\t\t<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.</p>\r\n");
      out.write("\t\t\t\t\t\t<ol class=\"terms_list\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \"de Finibus Bonorum et Malorum\".</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>Lusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati.</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>Praesentium voluptatum deleniti atque corrupti quos</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi.</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>Mentum eleifend enim a feugiat distinctio lor</li>\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t<h4>There are many variations of passages</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non libero magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat. Pellentesque viverra vehicula sem ut volutpat. Integer sed arcu. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non <a href=\"#\">libero consectetur adipiscing</a> elit magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat. Pellentesque viverra vehicula sem ut volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non libero magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat.</p>\r\n");
      out.write("\t\t\t\t\t\t<p><strong>Iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non sit amet, consectetur adipiscing elit. Ut adipiscing elit magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat. Pellentesque lorem ipsum dolor sit amet. Ut non libero magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat <a href=\"#\">consectetur adipiscing elit</a>.</strong></p>\r\n");
      out.write("\t\t\t\t\t  </div> \t\r\n");
      out.write("\t\t           </div>\r\n");
      out.write("\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t <div role=\"tabpanel\" class=\"tab-pane fade\" id=\"profile2\" aria-labelledby=\"profile-tab\">\r\n");
      out.write("\t\t\t\t    <div class=\"jobs-item with-thumb\">\r\n");
      out.write("\t                   <div class=\"thumb_top\">\r\n");
      out.write("\t\t\t\t        <div class=\"thumb\"><a href=\"view_profile.html\"><img src=\"images/s3.jpg\" class=\"img-responsive\" alt=\"\"/></a></div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"jobs_right\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"title\"><a href=\"view_profile.html\">Lorem (2547189)</a></h6>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"top-btns\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-facebook\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-twitter\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-google-plus\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"login_details1\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li>Last Login : 5 days ago</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"description\">30 years, 5 Ft 7 In / 170 Cms | <span class=\"m_1\">Reliogion</span> : Hindu | <span class=\"m_1\">Education</span> : B.Tech | <span class=\"m_1\">Occupation</span> : Software Professional<br><a href=\"view_profile.html\" class=\"read-more\">view full profile</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t   <div class=\"thumb_bottom\">\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"thumb\"><a href=\"view_profile.html\" class=\"photo_view\">Add Photo</a></div>\r\n");
      out.write("\t\t\t\t\t   \t   <div class=\"thumb_but\"><a href=\"view_profile.html\" class=\"photo_view\">Send Mail</a></div>\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"jobs-item with-thumb\">\r\n");
      out.write("\t                   <div class=\"thumb_top\">\r\n");
      out.write("\t\t\t\t        <div class=\"thumb\"><a href=\"view_profile.html\"><img src=\"images/s3.jpg\" class=\"img-responsive\" alt=\"\"/></a></div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"jobs_right\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"title\"><a href=\"view_profile.html\">Lorem (2547189)</a></h6>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"top-btns\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-facebook\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-twitter\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-google-plus\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"login_details1\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li>Last Login : 5 days ago</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"description\">30 years, 5 Ft 7 In / 170 Cms | <span class=\"m_1\">Reliogion</span> : Hindu | <span class=\"m_1\">Education</span> : B.Tech | <span class=\"m_1\">Occupation</span> : Software Professional<br><a href=\"view_profile.html\" class=\"read-more\">view full profile</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t   <div class=\"thumb_bottom\">\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"thumb\"><a href=\"view_profile.html\" class=\"photo_view\">Add Photo</a></div>\r\n");
      out.write("\t\t\t\t\t   \t   <div class=\"thumb_but\"><a href=\"view_profile.html\" class=\"photo_view\">Send Mail</a></div>\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"jobs-item with-thumb\">\r\n");
      out.write("\t                   <div class=\"thumb_top\">\r\n");
      out.write("\t\t\t\t        <div class=\"thumb\"><a href=\"view_profile.html\"><img src=\"images/s3.jpg\" class=\"img-responsive\" alt=\"\"/></a></div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"jobs_right\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"title\"><a href=\"view_profile.html\">Lorem (2547189)</a></h6>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"top-btns\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-facebook\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-twitter\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-google-plus\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"login_details1\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li>Last Login : 5 days ago</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"description\">30 years, 5 Ft 7 In / 170 Cms | <span class=\"m_1\">Reliogion</span> : Hindu | <span class=\"m_1\">Education</span> : B.Tech | <span class=\"m_1\">Occupation</span> : Software Professional<br><a href=\"view_profile.html\" class=\"read-more\">view full profile</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t   <div class=\"thumb_bottom\">\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"thumb\"><a href=\"view_profile.html\" class=\"photo_view\">Add Photo</a></div>\r\n");
      out.write("\t\t\t\t\t   \t   <div class=\"thumb_but\"><a href=\"view_profile.html\" class=\"photo_view\">Send Mail</a></div>\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"jobs-item with-thumb\">\r\n");
      out.write("\t                   <div class=\"thumb_top\">\r\n");
      out.write("\t\t\t\t        <div class=\"thumb\"><a href=\"view_profile.html\"><img src=\"images/s3.jpg\" class=\"img-responsive\" alt=\"\"/></a></div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"jobs_right\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"title\"><a href=\"view_profile.html\">Lorem (2547189)</a></h6>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"top-btns\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-facebook\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-twitter\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li><a href=\"#\" class=\"fa fa-google-plus\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"login_details1\">\r\n");
      out.write("\t\t\t\t\t\t\t  <li>Last Login : 5 days ago</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"description\">30 years, 5 Ft 7 In / 170 Cms | <span class=\"m_1\">Reliogion</span> : Hindu | <span class=\"m_1\">Education</span> : B.Tech | <span class=\"m_1\">Occupation</span> : Software Professional<br><a href=\"view_profile.html\" class=\"read-more\">view full profile</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t   <div class=\"thumb_bottom\">\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"thumb\"><a href=\"view_profile.html\" class=\"photo_view\">Add Photo</a></div>\r\n");
      out.write("\t\t\t\t\t   \t   <div class=\"thumb_but\"><a href=\"view_profile.html\" class=\"photo_view\">Send Mail</a></div>\r\n");
      out.write("\t\t\t\t\t   \t  <div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t <div role=\"tabpanel\" class=\"tab-pane fade\" id=\"profile3\" aria-labelledby=\"profile-tab\">\r\n");
      out.write("\t\t\t\t    <div class=\"terms\">\r\n");
      out.write("            \t\t  <h2>Your Privacy Settings</h2>\r\n");
      out.write("\t\t\t\t\t   <div class=\"terms_top\">\r\n");
      out.write("\t\t\t\t\t\t<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.</p>\r\n");
      out.write("\t\t\t\t\t\t<ol class=\"terms_list\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \"de Finibus Bonorum et Malorum\".</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>Lusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati.</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>Praesentium voluptatum deleniti atque corrupti quos</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi.</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>Mentum eleifend enim a feugiat distinctio lor</li>\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t<h4>There are many variations of passages</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non libero magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat. Pellentesque viverra vehicula sem ut volutpat. Integer sed arcu. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non <a href=\"#\">libero consectetur adipiscing</a> elit magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat. Pellentesque viverra vehicula sem ut volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non libero magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat.</p>\r\n");
      out.write("\t\t\t\t\t\t<p><strong>Iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non sit amet, consectetur adipiscing elit. Ut adipiscing elit magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat. Pellentesque lorem ipsum dolor sit amet. Ut non libero magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat <a href=\"#\">consectetur adipiscing elit</a>.</strong></p>\r\n");
      out.write("\t\t\t\t\t  </div> \t\r\n");
      out.write("\t\t           </div>\r\n");
      out.write("\t\t\t\t </div>\r\n");
      out.write("\t\t\t </div> \r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t   </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   <div class=\"clearfix\"> </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!----------------------------Content mid end------------------------------------------------------>\r\n");
      out.write("\r\n");
      out.write("<hr />    \r\n");
      out.write("   <!---------------------Footer------------------------->\r\n");
      out.write("<div class=\"row\" style=\"margin-top:2px;\">\r\n");
      out.write("           <div class=\"footer\">\r\n");
      out.write("    \t<div class=\"container\">\r\n");
      out.write("    \t\t<div class=\"col-md-4 col_2\">\r\n");
      out.write("    \t\t\t<h4>About Us</h4>\r\n");
      out.write("    \t\t\t<p>\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.\"</p>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"col-md-2 col_2\">\r\n");
      out.write("    \t\t\t<h4>Help & Support</h4>\r\n");
      out.write("    \t\t\t<ul class=\"footer_links\">\r\n");
      out.write("    \t\t\t\t<li><a href=\"#\">24x7 Live help</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"contact.html\">Contact us</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"#\">Feedback</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"faq.html\">FAQs</a></li>\r\n");
      out.write("    \t\t\t</ul>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"col-md-2 col_2\">\r\n");
      out.write("    \t\t\t<h4>Quick Links</h4>\r\n");
      out.write("    \t\t\t<ul class=\"footer_links\">\r\n");
      out.write("    \t\t\t\t<li><a href=\"privacy.html\">Privacy Policy</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"terms.html\">Terms and Conditions</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"services.html\">Services</a></li>\r\n");
      out.write("    \t\t\t</ul>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"col-md-2 col_2\">\r\n");
      out.write("    \t\t\t<h4>Social</h4>\r\n");
      out.write("    \t\t\t<ul class=\"footer_social\">\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\"><i class=\"fa fa-facebook fa1\"> </i></a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\"><i class=\"fa fa-twitter fa1\"> </i></a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\"><i class=\"fa fa-google-plus fa1\"> </i></a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\"><i class=\"fa fa-youtube fa1\"> </i></a></li>\r\n");
      out.write("\t\t\t    </ul>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("    \t\t<div class=\"copy\">\r\n");
      out.write("\t\t      <p>Copyright Â©  Marital . All Rights Reserved </p>\r\n");
      out.write("\t        </div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </div>\r\n");
      out.write(" </div>    \r\n");
      out.write("        \r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("// function to limt the length\r\n");
      out.write("function maxLengthCheck(object)\r\n");
      out.write("  {\r\n");
      out.write("    if (object.value.length > object.maxLength)\r\n");
      out.write("      object.value = object.value.slice(0, object.maxLength);\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    $(\".dropdown\").hover(            \r\n");
      out.write("        function() {\r\n");
      out.write("            $('.dropdown-menu', this).stop( true, true ).slideDown(\"fast\");\r\n");
      out.write("            $(this).toggleClass('open');        \r\n");
      out.write("        },\r\n");
      out.write("        function() {\r\n");
      out.write("            $('.dropdown-menu', this).stop( true, true ).slideUp(\"fast\");\r\n");
      out.write("            $(this).toggleClass('open');       \r\n");
      out.write("        }\r\n");
      out.write("    );\r\n");
      out.write("});\r\n");
      out.write("  \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
