/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-05-31 16:05:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/F:/Manobandhan/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MANOBANDHAN/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1589782556000L));
    _jspx_dependants.put("jar:file:/F:/Manobandhan/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MANOBANDHAN/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1589782554000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1589783439492L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--------------------------------------------------------------------\r\n");
      out.write("----------------------------------------------------------------------\r\n");
      out.write("\r\n");
      out.write("                        Manobandhan Index Page\r\n");
      out.write("            \r\n");
      out.write("-----------------------------------------------------------------------\r\n");
      out.write("----------------------------------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("  \r\n");
      out.write("  <title>MANOBANDHAN</title>\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"images/logo/Mano1.png\" type=\"image/x-icon\" />    \r\n");
      out.write("    <link href=\"css/temp.css\" rel=\"stylesheet\" type=\"text/css\"/>    \r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/home.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/font-awesome.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/bootstrap-3.1.1.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("        \r\n");
      out.write("    <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.flexisel.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script> \r\n");
      out.write("    <script src=\"js/login1.js\"></script> \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("\t  \r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write(".banner {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  \r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write(" \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".banner img {vertical-align: middle;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".banner .content {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  background: rgb(0, 0, 0); /* Fallback color */\r\n");
      out.write("  background: rgba(0, 0, 0, 0.5); /* Black background with 0.5 opacity */\r\n");
      out.write("  color: #f1f1f1;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  margin-bottom: 68px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".registration-button{\r\n");
      out.write("    color: white; \r\n");
      out.write("    width: auto; \r\n");
      out.write("    background-color:#FFC300; \r\n");
      out.write("    color: #ffffff; \r\n");
      out.write("    font-family:'A850-Roman'; \r\n");
      out.write("    font-size: 3em;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    margin-left:3px;\r\n");
      out.write("    padding-left: 2px;\r\n");
      out.write("}\r\n");
      out.write(".registration-button:hover{\r\n");
      out.write("    color: black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!---------------------header,Menu----------------------------------------------------------->\r\n");
      out.write("<!---------------------menu------------------------->\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\t<div class=\"col-lg-12 col-sm-12 col-md-12\" >\r\n");
      out.write("\t\t<nav class=\"nav navbar-default\" style=\"background-color:#AA3535;\">\r\n");
      out.write("\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-left\" style=\"font-family:'#44 Font';\">\r\n");
      out.write("\t\t\t\t\t<li ><a href=\"home.php\" style=\"color: white;\"><img src=\"images/logo/logo.png\" alt=\"Marital\" height=\"20px\"/></a></li>\t\t\t\t\t\t\t\t\r\n");
      out.write("                </ul>\r\n");
      out.write("\t\t        <ul class=\"nav navbar-nav navbar-right\" style=\"font-family:'#44 Font';\">                                                        \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\" data-toggle=\"modal\" data-target=\"#Login_model\" style=\"color: white;\"><i class=\"glyphicon glyphicon-user\"></i> Login</a></li>       \r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("      </div>     \t\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"errorMessage\" class=\"alert alert-danger text-center\">\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\t\t\r\n");
      out.write("<!---------------------Menu ends------------------------->\r\n");
      out.write(" <!-- Modal -->\r\n");
      out.write("<div id=\"Login_model\" class=\"modal fade\" role=\"dialog\">\r\n");
      out.write("\t<div class=\"modal-dialog\">\r\n");
      out.write("    <!-- Modal content-->\r\n");
      out.write("    \t<div class=\"modal-content\" style=\"border-radius: 25px;\">\r\n");
      out.write("    \t\t<div class=\"modal-head\" style=\"background-color:#AA3535;height: 45px; border-top-left-radius: 25px !important; border-top-right-radius: 25px !important;\">\r\n");
      out.write("    \t\t\t<center> <p style=\"font-family: Agnes; font-size: 2em; color: #ffffffff;\"><b>Manobandhan</b></p></center>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"modal-body\">\r\n");
      out.write("    \t\t\t<form method=\"post\" action=\"LoginInfo\">\r\n");
      out.write("    \t\t\t<!--  <form method=\"post\" action=\"LoginController\">\t -->             \r\n");
      out.write("      \t\t\t\t              \r\n");
      out.write("      \t\t\t<!----------personal info. form----------------->                                            \r\n");
      out.write("        \t\t\t<div class=\"form-group\">    \r\n");
      out.write("            \t\t\t<label for=\"username\" class=\"\"center\">Username:</label>               <!----------Username----------------->                                  \r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"firstname\" placeholder=\"Username\" name=\"username\" required/>                                                                                        \r\n");
      out.write("            </div>     \r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("            \t<label for=\"pasword\">Password:</label>            <!----------Password----------------->\r\n");
      out.write("                <input type=\"password\" class=\"form-control\" id=\"password\" placeholder=\"...........\" name=\"password\"required />                                            \r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary\"  name=\"submit\" style=\"margin-top: 2px;\">LOGIN</button>\r\n");
      out.write("            <a href=\"#\">Forgot your password?</a>\r\n");
      out.write("     \t</form>\r\n");
      out.write("  \t</div>      \t\t\t\r\n");
      out.write("    <div class=\"modal-footer\">\r\n");
      out.write("     \t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>                                        \r\n");
      out.write("     </div>\r\n");
      out.write("   </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>                         \r\n");
      out.write(" <!---------------------Menu ends------------------------->\r\n");
      out.write(" <!---------------------Banner------------------------->\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\t<div class=\"banner\">\r\n");
      out.write("    \t<img src=\"images/banner/b2.jpg\" alt=\"mariage\" style=\"width:100%\"  />\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("         \t<h1 style=\"font-family:'Alpha Echo';\">Find Your Match Here</h1>\r\n");
      out.write("            <a href=\"\" data-toggle=\"modal\" data-target=\"#Registration_model\" class=\"registration-button\" style=\"text-decoration:none; \">Register Free</a>\r\n");
      out.write("            <h5><a href=\"\" data-toggle=\"modal\" data-target=\"#Login_model\" style=\"color: #ffffffff; text-decoration:underline;\">Member Login</a></h5>    \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>  \r\n");
      out.write("<!---------------------Banner ends------------------------->\r\n");
      out.write("<!--------------------------------------------------------->\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div id=\"Registration_model\" class=\"modal fade\" role=\"dialog\">\r\n");
      out.write("\t<div class=\"modal-dialog\">\r\n");
      out.write("    \t<!-- Modal content-->\r\n");
      out.write("    \t<div class=\"modal-content\" style=\"border-radius: 25px;\">\r\n");
      out.write("     \t\t<div class=\"modal-head\" style=\"background-color:#AA3535;height: 45px; border-top-left-radius: 25px !important; border-top-right-radius: 25px !important;\">\r\n");
      out.write("            \t<center><p style=\"font-family: Agnes; font-size: 2em; color: #ffffffff;\"><b>Manobandhan</b></p></center>\r\n");
      out.write("            </div>\r\n");
      out.write("  \t\t \t\t\t\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("             \t<form method=\"post\" action=\"RegistrationServlet\">\t              \r\n");
      out.write("             \t<!----------personal info. form----------------->                                            \r\n");
      out.write("                 <div class=\"form-group\">                                        \r\n");
      out.write("                 \t<label for=\"username\">Username:</label>               <!----------Username----------------->                                  \r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"firstname\" placeholder=\"Username\" name=\"username\" required/>                                                                                        \r\n");
      out.write("                 </div>     \r\n");
      out.write("                 \r\n");
      out.write("                 <div class=\"form-group\">\r\n");
      out.write("                  \t<label for=\"password\">Password:</label>            <!----------Password----------------->\r\n");
      out.write("                     <input type=\"password\" class=\"form-control\" id=\"password\" placeholder=\"...........\" name=\"password\"required />                                            \r\n");
      out.write("                                          </div>\r\n");
      out.write("                                          \r\n");
      out.write("                                          <div class=\"form-group\">\r\n");
      out.write("                                            <label for=\"confirm_password\">Confirm Password:</label>            <!----------Password----------------->\r\n");
      out.write("                                            <input type=\"password\" class=\"form-control\" id=\"C_password\" placeholder=\"...........\" name=\"C_password\"required />                                            \r\n");
      out.write("                                          </div>\r\n");
      out.write("                                          \r\n");
      out.write("                                          <div class=\"form-group\">\r\n");
      out.write("                                            <label for=\"email\">Email:</label>            <!----------Password----------------->\r\n");
      out.write("                                            <input type=\"email\" class=\"form-control\" id=\"email\" placeholder=\"abc@xyz.com\" name=\"email\"required />                                            \r\n");
      out.write("                                          </div>                                                                                     \r\n");
      out.write("\r\n");
      out.write("                                          <div class=\"form-group\">\r\n");
      out.write("                                            <label for=\"contact\">Contact:</label>            <!----------Password----------------->\r\n");
      out.write("                                            <input type=\"number\" class=\"form-control\" id=\"Ccontact\" placeholder=\"xxx-xxxx-xxx\"  name=\"contact\" min=\"0\" maxlength=\"10\" oninput=\"maxLengthCheck(this)\" required />                                            \r\n");
      out.write("                                          </div> \r\n");
      out.write("                                                                                    \r\n");
      out.write("                                          <button type=\"submit\" class=\"btn btn-primary\"  name=\"submit\" style=\"margin-top: 2px;\">Register</button>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                      </div>      \t\t\t\r\n");
      out.write("                                      \r\n");
      out.write("                                      <div class=\"modal-footer\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>                                        \r\n");
      out.write("                                      </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                \r\n");
      out.write("                                  </div>\r\n");
      out.write("                                </div>                         \r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("               <!--------------------------------------------------------->\r\n");
      out.write("               \r\n");
      out.write("\r\n");
      out.write("<!--------------------------Success Story---------------------------------->\r\n");
      out.write("<div class=\"grid_2\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<h2>Success Stories</h2>\r\n");
      out.write("       \t<div class=\"heart-divider\">\r\n");
      out.write("\t\t\t<span class=\"grey-line\"></span>\r\n");
      out.write("\t\t\t<i class=\"fa fa-heart pink-heart\"></i>\r\n");
      out.write("\t\t\t<i class=\"fa fa-heart grey-heart\"></i>\r\n");
      out.write("\t\t\t<span class=\"grey-line\"></span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-8 suceess_story\">\r\n");
      out.write("\t         <ul> \r\n");
      out.write("\t\t\t   <li>\r\n");
      out.write("\t\t\t\t  \t<div class=\"suceess_story-date\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"entry-1\">Dec 20, 2015</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"suceess_story-content-container\">\r\n");
      out.write("\t\t\t\t\t\t<figure class=\"suceess_story-content-featured-image\">\r\n");
      out.write("\t\t\t\t\t\t   <img width=\"75\" height=\"75\" src=\"images/icon/7.jpg\" class=\"img-responsive\" alt=\"\"/>\t\t\t\t            \r\n");
      out.write("\t\t\t\t\t    </figure>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"suceess_story-content-info\">\r\n");
      out.write("\t\t\t\t        \t<h4><a href=\"#\">Lorem & Ipsum</a></h4>\t\t\t\t        \t\r\n");
      out.write("\t\t\t\t        \t<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form,.<a href=\"#\">More...</a></p>\r\n");
      out.write("\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t            <li>\r\n");
      out.write("\t\t\t\t  \t<div class=\"suceess_story-date\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"entry-1\">Dec 20, 2015</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"suceess_story-content-container\">\r\n");
      out.write("\t\t\t\t\t\t<figure class=\"suceess_story-content-featured-image\">\r\n");
      out.write("\t\t\t\t\t\t   <img width=\"75\" height=\"75\" src=\"images/icon/8.jpg\" class=\"img-responsive\" alt=\"\"/>\t\t\t\t            \r\n");
      out.write("\t\t\t\t\t    </figure>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"suceess_story-content-info\">\r\n");
      out.write("\t\t\t\t        \t<h4><a href=\"#\">Lorem & Ipsum</a></h4>\t\t\t\t        \t\r\n");
      out.write("\t\t\t\t        \t<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form,.<a href=\"#\">More...</a></p>\r\n");
      out.write("\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t            <li>\r\n");
      out.write("\t\t\t\t  \t<div class=\"suceess_story-date\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"entry-1\">Dec 20, 2015</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"suceess_story-content-container\">\r\n");
      out.write("\t\t\t\t\t\t<figure class=\"suceess_story-content-featured-image\">\r\n");
      out.write("\t\t\t\t\t\t   <img width=\"75\" height=\"75\" src=\"images/icon/9.jpg\" class=\"img-responsive\" alt=\"\"/>\t\t\t\t            \r\n");
      out.write("\t\t\t\t\t    </figure>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"suceess_story-content-info\">\r\n");
      out.write("\t\t\t\t        \t<h4><a href=\"#\">Lorem & Ipsum</a></h4>\t\t\t\t        \t\r\n");
      out.write("\t\t\t\t        \t<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form,.<a href=\"#\">More...</a></p>\r\n");
      out.write("\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t            <li>\r\n");
      out.write("\t\t\t\t  \t<div class=\"suceess_story-date\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"entry-1\">Dec 20, 2015</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"suceess_story-content-container\">\r\n");
      out.write("\t\t\t\t\t\t<figure class=\"suceess_story-content-featured-image\">\r\n");
      out.write("\t\t\t\t\t\t   <img width=\"75\" height=\"75\" src=\"images/icon/10.jpg\" class=\"img-responsive\" alt=\"\"/>\t\t\t\t            \r\n");
      out.write("\t\t\t\t\t    </figure>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"suceess_story-content-info\">\r\n");
      out.write("\t\t\t\t        \t<h4><a href=\"#\">Lorem & Ipsum</a></h4>\t\t\t\t        \t\r\n");
      out.write("\t\t\t\t        \t<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form,.<a href=\"#\">More...</a></p>\r\n");
      out.write("\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t            <li>\r\n");
      out.write("\t\t\t\t  \t<div class=\"suceess_story-date\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"entry-1\">Dec 20, 2015</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"suceess_story-content-container\">\r\n");
      out.write("\t\t\t\t\t\t<figure class=\"suceess_story-content-featured-image\">\r\n");
      out.write("\t\t\t\t\t\t   <img width=\"75\" height=\"75\" src=\"images/icon/11.jpg\" class=\"img-responsive\" alt=\"\"/>\t\t\t\t            \r\n");
      out.write("\t\t\t\t\t    </figure>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"suceess_story-content-info\">\r\n");
      out.write("\t\t\t\t        \t<h4><a href=\"#\">Lorem & Ipsum</a></h4>\t\t\t\t        \t\r\n");
      out.write("\t\t\t\t        \t<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form,.<a href=\"#\">More...</a></p>\r\n");
      out.write("\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t            <li>\r\n");
      out.write("\t\t\t\t  \t<div class=\"suceess_story-date\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"entry-1\">Dec 20, 2015</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"suceess_story-content-container\">\r\n");
      out.write("\t\t\t\t\t\t<figure class=\"suceess_story-content-featured-image\">\r\n");
      out.write("\t\t\t\t\t\t   <img width=\"75\" height=\"75\" src=\"images/icon/12.jpg\" class=\"img-responsive\" alt=\"\"/>\t\t\t\t            \r\n");
      out.write("\t\t\t\t\t    </figure>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"suceess_story-content-info\">\r\n");
      out.write("\t\t\t\t        \t<h4><a href=\"#\">Lorem & Ipsum</a></h4>\t\t\t\t        \t\r\n");
      out.write("\t\t\t\t        \t<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form,.<a href=\"#\">More...</a></p>\r\n");
      out.write("\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t            <li>\r\n");
      out.write("\t\t\t\t  \t<div class=\"suceess_story-date\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"entry-1\">Dec 20, 2015</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"suceess_story-content-container\">\r\n");
      out.write("\t\t\t\t\t\t<figure class=\"suceess_story-content-featured-image\">\r\n");
      out.write("\t\t\t\t\t\t   <img width=\"75\" height=\"75\" src=\"images/icon/13.jpg\" class=\"img-responsive\" alt=\"\"/>\t\t\t\t            \r\n");
      out.write("\t\t\t\t\t    </figure>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"suceess_story-content-info\">\r\n");
      out.write("\t\t\t\t        \t<h4><a href=\"#\">Lorem & Ipsum</a></h4>\t\t\t\t        \t\r\n");
      out.write("\t\t\t\t        \t<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form,.<a href=\"#\">More...</a></p>\r\n");
      out.write("\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t        </ul>\r\n");
      out.write("\t    </div>\r\n");
      out.write("        <div class=\"clearfix\"></div>\r\n");
      out.write("     </div>\r\n");
      out.write("   </div>\r\n");
      out.write(" </div>       \r\n");
      out.write("<!-------------------------Sucess Story ends------------------------------------------------>\r\n");
      out.write("\r\n");
      out.write("<!-------------------------Guest Message------------------------------------------------>\r\n");
      out.write("<div class=\"bg\">\r\n");
      out.write("\t\t<div class=\"container\"> \r\n");
      out.write("\t\t\t<h3>Guest Messages</h3>\r\n");
      out.write("\t\t\t<div class=\"heart-divider\">\r\n");
      out.write("\t\t\t\t<span class=\"grey-line\"></span>\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-heart pink-heart\"></i>\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-heart grey-heart\"></i>\r\n");
      out.write("\t\t\t\t<span class=\"grey-line\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-sm-6\">\r\n");
      out.write("            \t<div class=\"bg_left\">\r\n");
      out.write("            \t\t<h4>But I must explain</h4>\r\n");
      out.write("            \t\t<h5>Friend of Bride</h5>\r\n");
      out.write("            \t\t<p>\"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>\r\n");
      out.write("            \t   <ul class=\"team-socials\">\r\n");
      out.write("                    <li><a href=\"#\"><span class=\"icon-social \"><i class=\"fa fa-facebook\"></i></span></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><span class=\"icon-social \"><i class=\"fa fa-twitter\"></i></span></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><span class=\"icon-social\"><i class=\"fa fa-google-plus\"></i></span></a></li>\r\n");
      out.write("                   </ul>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-sm-6\">\r\n");
      out.write("            \t<div class=\"bg_left\">\r\n");
      out.write("            \t\t<h4>But I must explain</h4>\r\n");
      out.write("            \t\t<h5>Friend of Groom</h5>\r\n");
      out.write("            \t\t<p>\"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>\r\n");
      out.write("            \t   <ul class=\"team-socials\">\r\n");
      out.write("                    <li><a href=\"#\"><span class=\"icon-social \"><i class=\"fa fa-facebook\"></i></span></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><span class=\"icon-social \"><i class=\"fa fa-twitter\"></i></span></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><span class=\"icon-social\"><i class=\"fa fa-google-plus\"></i></span></a></li>\r\n");
      out.write("                   </ul>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-------------------------Guest Message Ends------------------------------------------------>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("   <!---------------------Footer------------------------->\r\n");
      out.write("<div class=\"row\" style=\"margin-top:2px;\">\r\n");
      out.write("           <div class=\"footer\">\r\n");
      out.write("    \t<div class=\"container\">\r\n");
      out.write("    \t\t<div class=\"col-md-4 col_2\">\r\n");
      out.write("    \t\t\t<h4>About Us</h4>\r\n");
      out.write("    \t\t\t<p>\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.\"</p>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"col-md-2 col_2\">\r\n");
      out.write("    \t\t\t<h4>Help & Support</h4>\r\n");
      out.write("    \t\t\t<ul class=\"footer_links\">\r\n");
      out.write("    \t\t\t\t<li><a href=\"#\">24x7 Live help</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"about.jsp\">Contact us</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"#\">Feedback</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"faq.jsp\">FAQs</a></li>\r\n");
      out.write("    \t\t\t</ul>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"col-md-2 col_2\">\r\n");
      out.write("    \t\t\t<h4>Quick Links</h4>\r\n");
      out.write("    \t\t\t<ul class=\"footer_links\">\r\n");
      out.write("    \t\t\t\t<li><a href=\"privacy.jsp\">Privacy Policy</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"terms.jsp\">Terms and Conditions</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"services.jsp\">Services</a></li>\r\n");
      out.write("    \t\t\t</ul>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"col-md-2 col_2\">\r\n");
      out.write("    \t\t\t<h4>Social</h4>\r\n");
      out.write("    \t\t\t<ul class=\"footer_social\">\r\n");
      out.write("\t\t\t\t  <li><a href=\"www.facebook.com\"><i class=\"fa fa-facebook fa1\"> </i></a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"www.twitter.com\"><i class=\"fa fa-twitter fa1\"> </i></a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"www.gmail.com\"><i class=\"fa fa-google-plus fa1\"> </i></a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"www.youtube.com\"><i class=\"fa fa-youtube fa1\"> </i></a></li>\r\n");
      out.write("\t\t\t    </ul>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("    \t\t<div class=\"copy\">\r\n");
      out.write("\t\t      <p>Copyright ©  Marital . All Rights Reserved </p>\r\n");
      out.write("\t        </div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </div>\r\n");
      out.write(" </div>    \r\n");
      out.write("        \r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("// function to limt the length\r\n");
      out.write("function maxLengthCheck(object) {\r\n");
      out.write("  if (object.value.length > object.maxLength)\r\n");
      out.write("      object.value = object.value.slice(0, object.maxLength);\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write(" setTimeout(function() {\r\n");
      out.write("    $(\"#errorMessage\").fadeTo(500, 0).slideUp(500, function(){\r\n");
      out.write("        $(this).remove();   \r\n");
      out.write("    });\r\n");
      out.write("}, 3000); \r\n");
      out.write("}); \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /index.jsp(98,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty message}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t<h5>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h5>\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
