/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-05-31 04:27:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class matches_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--------------------------------------------------------------------\r\n");
      out.write("----------------------------------------------------------------------\r\n");
      out.write("\r\n");
      out.write("                        Manobandhan Matches Page\r\n");
      out.write("            \r\n");
      out.write("-----------------------------------------------------------------------\r\n");
      out.write("----------------------------------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("  \r\n");
      out.write("  <title>Manobandhan</title>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"images/logo/Mano1.png\" type=\"image/x-icon\" />    \r\n");
      out.write("    <link href=\"css/temp.css\" rel=\"stylesheet\" type=\"text/css\"/>    \r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/home.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/font-awesome.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/bootstrap-3.1.1.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\"/>    \r\n");
      out.write("        <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"js/jquery.flexisel.js\"></script>\r\n");
      out.write("        <script src=\"js/bootstrap.min.js\"></script> \r\n");
      out.write("        <script src=\"js/login1.js\"></script>      \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write(" \t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("   \r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write(".banner {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  \r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write(" \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".banner img {vertical-align: middle;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".banner .content {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  background: rgb(0, 0, 0); /* Fallback color */\r\n");
      out.write("  background: rgba(0, 0, 0, 0.5); /* Black background with 0.5 opacity */\r\n");
      out.write("  color: #f1f1f1;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  margin-bottom: 68px;\r\n");
      out.write("}\r\n");
      out.write(".profile-picture {\r\n");
      out.write("\tborder-radius: 100%;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\t-webkit-box-sizing: content-box;\r\n");
      out.write("  \t-moz-box-sizing: content-box;\r\n");
      out.write("  \tbox-sizing: content-box;\t\r\n");
      out.write("}\r\n");
      out.write("\t.small-profile-picture {\r\n");
      out.write("\t\tborder: 2px solid #50597b;\r\n");
      out.write("\t\twidth: 40px;\r\n");
      out.write("\t\theight: 40px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.big-profile-picture {\r\n");
      out.write("\t\tmargin: 0 auto;\t\t\r\n");
      out.write("\t\tborder: 5px solid #50597b;\r\n");
      out.write("\t\twidth: 150px;\r\n");
      out.write("\t\theight: 150px;\r\n");
      out.write("        \r\n");
      out.write("\t}\r\n");
      out.write("    \r\n");
      out.write(".nav-tabs > li > a, \r\n");
      out.write(".nav-tabs > li > a:hover, \r\n");
      out.write(".nav-tabs > li > a:focus, \r\n");
      out.write(".nav-tabs > li.active > a, \r\n");
      out.write(".nav-tabs > li.active > a:hover,\r\n");
      out.write(".nav-tabs > li.active > a:focus {\r\n");
      out.write("  border: none;\r\n");
      out.write("  border-radius: 0;\r\n");
      out.write("  background-color:#ffa417;\r\n");
      out.write("}    \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<!---------------------header,Menu----------------------------------------------------------->\r\n");
      out.write("    \r\n");
      out.write("\t              <!---------------------menu------------------------->\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t           <!---------------------Menu ends------------------------->\r\n");
      out.write("                           \r\n");
      out.write("            <!---------------------content mid------------------------->\r\n");
      out.write("<div class=\"grid_3\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("   <div class=\"breadcrumb1\">\r\n");
      out.write("     <ul>\r\n");
      out.write("        <a href=\"profile.jsp\"><i class=\"fa fa-home home_1\"></i></a>\r\n");
      out.write("        <span class=\"divider\">&nbsp;|&nbsp;</span>\r\n");
      out.write("        <li class=\"current-page\"><h3>New Matches</h3></li>\r\n");
      out.write("     </ul>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"col-md-9 profile_left2\">\r\n");
      out.write("     <form>\r\n");
      out.write("\t  <div class=\"form_but2\">\r\n");
      out.write("\t\t<label class=\"col-md-2 control-lable1\" for=\"sex\">Don't Show : </label>\r\n");
      out.write("\t\t<div class=\"col-md-10 form_radios\">\r\n");
      out.write("\t\t\t<input type=\"checkbox\" class=\"radio_1\"> Don't show already viewed &nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t<input type=\"checkbox\" class=\"radio_1\" checked=\"checked\"> Don't show already contacted &nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t<input type=\"checkbox\" class=\"radio_1\" checked=\"checked\"> Show profiles with photo\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t </form>\r\n");
      out.write("\t <div class=\"profile_top\"><a href=\"view_profile.html\">\r\n");
      out.write("      <h2>254879 | Profile Created for self</h2>\r\n");
      out.write("\t    <div class=\"col-sm-3 profile_left-top\">\r\n");
      out.write("\t    \t<img src=\"images/a5.jpg\" class=\"img-responsive\" alt=\"\"/>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t      <ul class=\"login_details1\">\r\n");
      out.write("\t\t\t <li>Last Login : 5 days ago</li>\r\n");
      out.write("\t\t\t <li><p>\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.\" More....</p></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"col-sm-6\">\r\n");
      out.write("\t    \t<table class=\"table_working_hours\">\r\n");
      out.write("\t        \t<tbody>\r\n");
      out.write("\t        \t\t<tr class=\"opened_1\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Age / Height :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">28, 5ft 5in / 163cm</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"opened\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Last Login :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">4 hours ago</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"opened\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Religion :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">Sikh</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"opened\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Marital Status :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">Single</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"opened\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Location :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">India</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"closed\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Profile Created by :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value closed\"><span>Self</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"closed\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Education :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value closed\"><span>Engineering</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t    </tbody>\r\n");
      out.write("\t\t   </table>\r\n");
      out.write("\t\t   <div class=\"buttons\">\r\n");
      out.write("\t\t\t   <div class=\"vertical\">Send Mail</div>\r\n");
      out.write("\t\t\t   <div class=\"vertical\">Shortlisted</div>\r\n");
      out.write("\t\t\t   <div class=\"vertical\">Send Interest</div>\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"clearfix\"> </div>\r\n");
      out.write("    </a></div>\r\n");
      out.write("    <div class=\"profile_top\"><a href=\"view_profile.html\">\r\n");
      out.write("      <h2>254879 | Profile Created for self</h2>\r\n");
      out.write("\t    <div class=\"col-sm-3 profile_left-top\">\r\n");
      out.write("\t    \t<img src=\"images/a6.jpg\" class=\"img-responsive\" alt=\"\"/>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t      <ul class=\"login_details1\">\r\n");
      out.write("\t\t\t <li>Last Login : 5 days ago</li>\r\n");
      out.write("\t\t\t <li><p>\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.\" More....</p></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"col-sm-6\">\r\n");
      out.write("\t    \t<table class=\"table_working_hours\">\r\n");
      out.write("\t        \t<tbody>\r\n");
      out.write("\t        \t\t<tr class=\"opened_1\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Age / Height :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">28, 5ft 5in / 163cm</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"opened\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Last Login :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">4 hours ago</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"opened\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Religion :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">Sikh</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"opened\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Marital Status :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">Single</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"opened\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Location :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">India</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"closed\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Profile Created by :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value closed\"><span>Self</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"closed\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Education :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value closed\"><span>Engineering</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t    </tbody>\r\n");
      out.write("\t\t   </table>\r\n");
      out.write("\t\t   <div class=\"buttons\">\r\n");
      out.write("\t\t\t   <div class=\"vertical\">Send Mail</div>\r\n");
      out.write("\t\t\t   <div class=\"vertical\">Shortlisted</div>\r\n");
      out.write("\t\t\t   <div class=\"vertical\">Send Interest</div>\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"clearfix\"> </div>\r\n");
      out.write("    </a></div>\r\n");
      out.write("    <div class=\"profile_top\"><a href=\"view_profile.html\">\r\n");
      out.write("      <h2>254879 | Profile Created for self</h2>\r\n");
      out.write("\t    <div class=\"col-sm-3 profile_left-top\">\r\n");
      out.write("\t    \t<img src=\"images/a7.jpg\" class=\"img-responsive\" alt=\"\">\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t      <ul class=\"login_details1\">\r\n");
      out.write("\t\t\t <li>Last Login : 5 days ago</li>\r\n");
      out.write("\t\t\t <li><p>\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.\" More....</p></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"col-sm-6\">\r\n");
      out.write("\t    \t<table class=\"table_working_hours\">\r\n");
      out.write("\t        \t<tbody>\r\n");
      out.write("\t        \t\t<tr class=\"opened_1\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Age / Height :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">28, 5ft 5in / 163cm</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"opened\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Last Login :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">4 hours ago</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"opened\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Religion :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">Sikh</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"opened\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Marital Status :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">Single</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"opened\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Location :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">India</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"closed\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Profile Created by :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value closed\"><span>Self</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"closed\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Education :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value closed\"><span>Engineering</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t    </tbody>\r\n");
      out.write("\t\t   </table>\r\n");
      out.write("\t\t   <div class=\"buttons\">\r\n");
      out.write("\t\t\t   <div class=\"vertical\">Send Mail</div>\r\n");
      out.write("\t\t\t   <div class=\"vertical\">Shortlisted</div>\r\n");
      out.write("\t\t\t   <div class=\"vertical\">Send Interest</div>\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"clearfix\"> </div>\r\n");
      out.write("    </a></div>\r\n");
      out.write("    <div class=\"profile_top\"><a href=\"view_profile.html\">\r\n");
      out.write("      <h2>254879 | Profile Created for self</h2>\r\n");
      out.write("\t    <div class=\"col-sm-3 profile_left-top\">\r\n");
      out.write("\t    \t<img src=\"images/a5.jpg\" class=\"img-responsive\" alt=\"\"/>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t      <ul class=\"login_details1\">\r\n");
      out.write("\t\t\t <li>Last Login : 5 days ago</li>\r\n");
      out.write("\t\t\t <li><p>\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.\" More....</p></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"col-sm-6\">\r\n");
      out.write("\t    \t<table class=\"table_working_hours\">\r\n");
      out.write("\t        \t<tbody>\r\n");
      out.write("\t        \t\t<tr class=\"opened_1\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Age / Height :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">28, 5ft 5in / 163cm</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"opened\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Last Login :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">4 hours ago</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"opened\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Religion :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">Sikh</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"opened\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Marital Status :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">Single</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"opened\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Location :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">India</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"closed\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Profile Created by :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value closed\"><span>Self</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"closed\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Education :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value closed\"><span>Engineering</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t    </tbody>\r\n");
      out.write("\t\t   </table>\r\n");
      out.write("\t\t   <div class=\"buttons\">\r\n");
      out.write("\t\t\t   <div class=\"vertical\">Send Mail</div>\r\n");
      out.write("\t\t\t   <div class=\"vertical\">Shortlisted</div>\r\n");
      out.write("\t\t\t   <div class=\"vertical\">Send Interest</div>\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"clearfix\"> </div>\r\n");
      out.write("    </a></div>\r\n");
      out.write("    <div class=\"profile_top profile_top1\"><a href=\"view_profile.html\">\r\n");
      out.write("      <h2>254879 | Profile Created for self</h2>\r\n");
      out.write("\t    <div class=\"col-sm-3 profile_left-top\">\r\n");
      out.write("\t    \t<img src=\"images/a8.jpg\" class=\"img-responsive\" alt=\"\"/>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t      <ul class=\"login_details1\">\r\n");
      out.write("\t\t\t <li>Last Login : 5 days ago</li>\r\n");
      out.write("\t\t\t <li><p>\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.\" More....</p></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"col-sm-6\">\r\n");
      out.write("\t    \t<table class=\"table_working_hours\">\r\n");
      out.write("\t        \t<tbody>\r\n");
      out.write("\t        \t\t<tr class=\"opened_1\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Age / Height :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">28, 5ft 5in / 163cm</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"opened\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Last Login :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">4 hours ago</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"opened\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Religion :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">Sikh</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"opened\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Marital Status :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">Single</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"opened\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Location :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value\">India</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"closed\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Profile Created by :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value closed\"><span>Self</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr class=\"closed\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_label1\">Education :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"day_value closed\"><span>Engineering</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t    </tbody>\r\n");
      out.write("\t\t   </table>\r\n");
      out.write("\t\t   <div class=\"buttons\">\r\n");
      out.write("\t\t\t   <div class=\"vertical\">Send Mail</div>\r\n");
      out.write("\t\t\t   <div class=\"vertical\">Shortlisted</div>\r\n");
      out.write("\t\t\t   <div class=\"vertical\">Send Interest</div>\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"clearfix\"> </div>\r\n");
      out.write("    </a></div>\r\n");
      out.write("    <ul class=\"pagination\">\r\n");
      out.write(" \t  <li class=\"active\"><a href=\"#\">1</a></li>\r\n");
      out.write(" \t  <li><a href=\"#\">2</a></li>\r\n");
      out.write(" \t  <li><a href=\"#\">3</a></li>\r\n");
      out.write(" \t  <li><a href=\"#\">4</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-md-3 match_right\">\r\n");
      out.write("    <ul class=\"menu\">\r\n");
      out.write("\t\t<li class=\"item1\"><h3 class=\"m_2\">Show Profiles Created</h3>\r\n");
      out.write("\t\t  <ul class=\"cute\">\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">within a week (2) </a></li>\r\n");
      out.write("\t\t\t<li class=\"subitem2\"><a href=\"#\">within a month (4)</a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"item1\"><h3 class=\"m_2\">Profile type</h3>\r\n");
      out.write("\t\t  <ul class=\"cute\">\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">with Photo (3) </a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"item1\"><h3 class=\"m_2\">Marital Status</h3>\r\n");
      out.write("\t\t  <ul class=\"cute\">\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Unmarried (2) </a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"item1\"><h3 class=\"m_2\">Mother Tongue</h3>\r\n");
      out.write("\t\t  <ul class=\"cute\">\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">English </a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"item1\"><h3 class=\"m_2\">Education</h3>\r\n");
      out.write("\t\t  <ul class=\"cute\">\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Bachelors-Engineering </a></li>\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Masters-Engineering </a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"item1\"><h3 class=\"m_2\">Occupation</h3>\r\n");
      out.write("\t\t  <ul class=\"cute\">\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Engineer-Non IT (2) </a></li>\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Software Professional (3)</a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"item1\"><h3 class=\"m_2\">Physical Status</h3>\r\n");
      out.write("\t\t  <ul class=\"cute\">\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Normal (2) </a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"item1\"><h3 class=\"m_2\">Eating Habits</h3>\r\n");
      out.write("\t\t  <ul class=\"cute\">\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Non Vegetarian (3)</a></li>\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Vegetarian (2)</a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"item1\"><h3 class=\"m_2\">Smoking</h3>\r\n");
      out.write("\t\t  <ul class=\"cute\">\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Not Specified (3)</a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"item1\"><h3 class=\"m_2\">Drinking</h3>\r\n");
      out.write("\t\t  <ul class=\"cute\">\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Not Specified (3)</a></li>\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Never Drinks (3)</a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"item1\"><h3 class=\"m_2\">Profile Created by</h3>\r\n");
      out.write("\t\t  <ul class=\"cute\">\r\n");
      out.write("\t\t\t<li class=\"subitem1\"><a href=\"#\">Self (1)</a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t  </ul>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"clearfix\"> </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <!---------------------content mid ends------------------------->\r\n");
      out.write("<hr />\r\n");
      out.write("   <!---------------------Footer------------------------->\r\n");
      out.write("<div class=\"row\" style=\"margin-top:2px;\">\r\n");
      out.write("           <div class=\"footer\">\r\n");
      out.write("    \t<div class=\"container\">\r\n");
      out.write("    \t\t<div class=\"col-md-4 col_2\">\r\n");
      out.write("    \t\t\t<h4>About Us</h4>\r\n");
      out.write("    \t\t\t<p>\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.\"</p>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"col-md-2 col_2\">\r\n");
      out.write("    \t\t\t<h4>Help & Support</h4>\r\n");
      out.write("    \t\t\t<ul class=\"footer_links\">\r\n");
      out.write("    \t\t\t\t<li><a href=\"#\">24x7 Live help</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"contact.html\">Contact us</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"#\">Feedback</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"faq.html\">FAQs</a></li>\r\n");
      out.write("    \t\t\t</ul>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"col-md-2 col_2\">\r\n");
      out.write("    \t\t\t<h4>Quick Links</h4>\r\n");
      out.write("    \t\t\t<ul class=\"footer_links\">\r\n");
      out.write("    \t\t\t\t<li><a href=\"privacy.html\">Privacy Policy</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"terms.html\">Terms and Conditions</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"services.html\">Services</a></li>\r\n");
      out.write("    \t\t\t</ul>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"col-md-2 col_2\">\r\n");
      out.write("    \t\t\t<h4>Social</h4>\r\n");
      out.write("    \t\t\t<ul class=\"footer_social\">\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\"><i class=\"fa fa-facebook fa1\"> </i></a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\"><i class=\"fa fa-twitter fa1\"> </i></a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\"><i class=\"fa fa-google-plus fa1\"> </i></a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"#\"><i class=\"fa fa-youtube fa1\"> </i></a></li>\r\n");
      out.write("\t\t\t    </ul>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("    \t\t<div class=\"copy\">\r\n");
      out.write("\t\t      <p>Copyright Â©  Marital . All Rights Reserved </p>\r\n");
      out.write("\t        </div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </div>\r\n");
      out.write(" </div>    \r\n");
      out.write("        \r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("// function to limt the length\r\n");
      out.write("function maxLengthCheck(object)\r\n");
      out.write("  {\r\n");
      out.write("    if (object.value.length > object.maxLength)\r\n");
      out.write("      object.value = object.value.slice(0, object.maxLength);\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    $(\".dropdown\").hover(            \r\n");
      out.write("        function() {\r\n");
      out.write("            $('.dropdown-menu', this).stop( true, true ).slideDown(\"fast\");\r\n");
      out.write("            $(this).toggleClass('open');        \r\n");
      out.write("        },\r\n");
      out.write("        function() {\r\n");
      out.write("            $('.dropdown-menu', this).stop( true, true ).slideUp(\"fast\");\r\n");
      out.write("            $(this).toggleClass('open');       \r\n");
      out.write("        }\r\n");
      out.write("    );\r\n");
      out.write("});\r\n");
      out.write("  \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
