/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-06-01 17:03:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--------------------------------------------------------------------\r\n");
      out.write("----------------------------------------------------------------------\r\n");
      out.write("\r\n");
      out.write("                        Manobandhan Profile Page\r\n");
      out.write("            \r\n");
      out.write("-----------------------------------------------------------------------\r\n");
      out.write("----------------------------------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("  \r\n");
      out.write("  <title>MANOBANDHAN</title>\r\n");
      out.write("    \r\n");
      out.write("   <link rel=\"shortcut icon\" href=\"images/logo/Mano1.png\" type=\"image/x-icon\" />     \r\n");
      out.write("    <link href=\"css/flexslider.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/home.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/font-awesome.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/bootstrap-3.1.1.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\"/>    \r\n");
      out.write("    <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.flexisel.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script> \r\n");
      out.write("    <script src=\"js/login1.js\"></script>   \r\n");
      out.write("        \r\n");
      out.write("   <script type=\"text/javascript\">\\\r\n");
      out.write("   <!--\r\n");
      out.write("    $(document).on(\"click\", \".bedit\", function(){\r\n");
      out.write("    \t\r\n");
      out.write("    \tconsole.log(\"Function\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\tcall\");\r\n");
      out.write("    \t\r\n");
      out.write("    \tvar $this = $(this);\r\n");
      out.write(" \r\n");
      out.write("    \tif ($this.html() === 'Edit') {\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tconsole.log(\"Edit call\");\r\n");
      out.write("    \t\t$this.html('Save');\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t$(\".basicDetails\").prop('contenteditable', true);\r\n");
      out.write("    \t} else {\r\n");
      out.write("    \t\tconsole.log(\"Save call\");\r\n");
      out.write("    \t\t$this.html('Edit');\r\n");
      out.write("    \t\t$(\".basicDetails\").prop('contenteditable', false);\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tvar bname = $(\"#bname\").text();\r\n");
      out.write("    \t\t$('input[name=\"name\"]').val()=bname;\r\n");
      out.write("    \t\tconsole.log(bname);\r\n");
      out.write("    \t}\r\n");
      out.write("   \t});-->\r\n");
      out.write("    </script>   \r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write(".banner {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  \r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write(" \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".banner img {vertical-align: middle;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".banner .content {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  background: rgb(0, 0, 0); /* Fallback color */\r\n");
      out.write("  background: rgba(0, 0, 0, 0.5); /* Black background with 0.5 opacity */\r\n");
      out.write("  color: #f1f1f1;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  margin-bottom: 68px;\r\n");
      out.write("}\r\n");
      out.write(".profile-picture {\r\n");
      out.write("\tborder-radius: 100%;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\t-webkit-box-sizing: content-box;\r\n");
      out.write("  \t-moz-box-sizing: content-box;\r\n");
      out.write("  \tbox-sizing: content-box;\t\r\n");
      out.write("}\r\n");
      out.write("\t.small-profile-picture {\r\n");
      out.write("\t\tborder: 2px solid #50597b;\r\n");
      out.write("\t\twidth: 40px;\r\n");
      out.write("\t\theight: 40px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.big-profile-picture {\r\n");
      out.write("\t\tmargin: 0 auto;\t\t\r\n");
      out.write("\t\tborder: 5px solid #50597b;\r\n");
      out.write("\t\twidth: 150px;\r\n");
      out.write("\t\theight: 150px;\r\n");
      out.write("        \r\n");
      out.write("\t}\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</style>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<!---------------------header,Menu----------------------------------------------------------->\r\n");
      out.write("    \r\n");
      out.write("\t              <!---------------------menu------------------------->\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-12 col-sm-12 col-md-12\" >\r\n");
      out.write("\t\t\t\t<nav class=\"nav navbar-default\" style=\"background-color:#AA3535;  width: 100%;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav navbar-nav navbar-left\" style=\"font-family:'#44 Font';\"><!----left--->\r\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"profile.jsp\" style=\"color: white;\">Home</a></li>\r\n");
      out.write("                            <li ><a href=\"matches.jsp\" style=\"color: white;\">Matches</a></li>\r\n");
      out.write("                            <li ><a href=\"inbox.jsp\" style=\"color: white;\">Inbox</a></li>\r\n");
      out.write("                            <li ><a href=\"search.jsp\" style=\"color: white;\">Search</a></li>\r\n");
      out.write("                            <li ><a href=\"upgrade.jsp\" style=\"color: white;\">Premium1</a></li>\r\n");
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav navbar-nav\" style=\"font-family:'#44 Font'; margin-left: 20%;\">  <!----Center--->\r\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"profile.jsp\" style=\"color: white;\"><img src=\"images/logo/logo.png\" alt=\"Marital\" height=\"25\"/></a></li>\r\n");
      out.write("                        </ul>                            \r\n");
      out.write("\t\t                 <ul class=\"nav navbar-nav navbar-right\" style=\"font-family:'#44 Font'; margin-right: 10px; margin-top: 4px;\">  <!----right--->                                                        \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\" data-toggle=\"modal\" data-target=\"#Login_model\" style=\"color: white;\"></span>My Profile</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("                            <div class=\"profile-picture small-profile-picture\">                                \r\n");
      out.write("                                <img width=\"40px\" alt=\"Anne Hathaway picture\" src=\"data:image/jpeg;base64,");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${photo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">                                \r\n");
      out.write("                            </div>                                   \r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("           </div>     \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\r\n");
      out.write("\t           <!---------------------Menu ends------------------------->   \r\n");
      out.write("     <div class=\"row\" style=\"margin-top: 5px;\">  \r\n");
      out.write("       <div class=\"col-lg-3 col-md-3 col-sm-12\">  <!-----left prfile------------------->    \r\n");
      out.write("           \r\n");
      out.write("              <div class=\"card\" style=\"margin-top: 5px;\">           \r\n");
      out.write("                     <div class=\"flexslider\">\r\n");
      out.write("    \t\t\t\t\t <ul class=\"slides\">\r\n");
      out.write("                         <img width=\"100px\" alt=\"Anne Hathaway picture\" src=\"data:image/jpeg;base64,");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${photo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("    \t\t\t\t\t\t<li data-thumb=\"images/icon/p1.jpg\">\r\n");
      out.write("    \t\t\t\t\t\t\t<img src=\"images/icon/a1.jpg\" />\r\n");
      out.write("    \t\t\t\t\t\t</li>\r\n");
      out.write("    \t\t\t\t\t\t<li data-thumb=\"images/icon/p2.jpg\">\r\n");
      out.write("    \t\t\t\t\t\t\t<img src=\"images/icon/p2.jpg\" />\r\n");
      out.write("    \t\t\t\t\t\t</li>\r\n");
      out.write("    \t\t\t\t\t\t<li data-thumb=\"images/icon/p3.jpg\">\r\n");
      out.write("    \t\t\t\t\t\t\t<img src=\"images/icon/p3.jpg\" />\r\n");
      out.write("    \t\t\t\t\t\t</li>\r\n");
      out.write("    \t\t\t\t\t\t<li data-thumb=\"images/icon/p4.jpg\">\r\n");
      out.write("    \t\t\t\t\t\t\t<img src=\"images/icon/p4.jpg\" />\r\n");
      out.write("    \t\t\t\t\t\t</li>\r\n");
      out.write("    \t\t\t\t\t </ul>\r\n");
      out.write("                      </div>                      \r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"card\" style=\"margin-top: -22px;\" >           <!----------Critical Detail---------->\r\n");
      out.write("                      <div class=\"card-header\" style=\"margin-top: 5px;\">           \r\n");
      out.write("                         <p style=\"font-family: Agnes; font-size: 2em;\"><b>Critical Detail</b></p>      \r\n");
      out.write("                         <button class=\"btn-sm btn-danger\"> Edit</button>            \r\n");
      out.write("                      </div>\r\n");
      out.write("                      \r\n");
      out.write("                      <div class=\"card-content\" style=\"margin-top: 5px;\">           \r\n");
      out.write("                    <table class=\"table\">\r\n");
      out.write("                   <a href='EditServlet?id=\"+5+\"'><button type=\"button\">edit</button></a>\r\n");
      out.write("    \t\t        \t<tbody>    \t\t        \t\t\t\t\t\t   \t\t\t\t\t\t                   \r\n");
      out.write("    \t\t\t\t\t    <tr>\r\n");
      out.write("    \t\t\t\t\t\t\t<th><b>Age :</b></th>\r\n");
      out.write("    \t\t\t\t\t\t\t<!-- <td ><input type=\"number\" >");
      out.print( session.getAttribute("age") );
      out.write("</td> -->\r\n");
      out.write("    \t\t\t\t\t\t\t<td contenteditable=\"false\">");
      out.print( session.getAttribute("age") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t    <tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<th><b>Marital Status :</b></th>\r\n");
      out.write("    \t\t\t\t\t\t\t<td contenteditable=\"false\">");
      out.print( session.getAttribute("marital_status") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>   \r\n");
      out.write("    \t\t\t\t\t\t \r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t    \r\n");
      out.write("    \t\t\t\t    </tbody>                        \r\n");
      out.write("\t\t\t\t</table>   \r\n");
      out.write("\t\t\t\t                                      \r\n");
      out.write("                    </div>    \r\n");
      out.write("                                                                              \r\n");
      out.write("              </div>     \r\n");
      out.write("               <div class=\"card\" style=\"margin-top: -22px;\" >           <!----------Critical Detail---------->\r\n");
      out.write("                      <div class=\"card-header\" style=\"margin-top: 5px;\">           \r\n");
      out.write("                         <p style=\"font-family: Agnes; font-size: 2em;\"><b>Basic Detail</b></p>\r\n");
      out.write("                         <form>\r\n");
      out.write("                         \t<button class=\"btn-sm btn-primary bedit\"> Edit</button>\r\n");
      out.write("                         \t<input type=\"hidden\" name =\"name\" id=\"name\" value=\"\">\r\n");
      out.write("                         \t<input type=\"hidden\" name =\"height\" id=\"height\" value=\"\">\r\n");
      out.write("                         \t<input type=\"hidden\" name =\"weight\" id=\"weight\" value=\"\">\r\n");
      out.write("                         \t<input type=\"hidden\" name =\"Mother_tongue\" id=\"Mother_tongue\" value=\"\">\r\n");
      out.write("                         \t<input type=\"hidden\" name =\"caste\" id=\"caste\" value=\"\">\r\n");
      out.write("                         \t<input type=\"hidden\" name =\"Annual_Income\" id=\"Annual_Income\" value=\"\">\r\n");
      out.write("                         \t<input type=\"hidden\" name =\"profilemanageby\" id=\"profilemanageby\" value=\"\">\r\n");
      out.write("                         \t\r\n");
      out.write("                         </form>               \r\n");
      out.write("                      </div>\r\n");
      out.write("                      \r\n");
      out.write("                      <div class=\"card-content\" style=\"margin-top: 5px;\">           \r\n");
      out.write("                    <table class=\"table\">\r\n");
      out.write("    \t\t        \t<tbody>   \r\n");
      out.write("    \t\t\t\t\t   <tr>\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Full Name :</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td id=\"bname\" class=\"basicDetails\" contenteditable=\"false\">");
      out.print( session.getAttribute("name") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t    <tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td ><b>Height :</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td  class=\"basicDetails\" contenteditable=\"false\">");
      out.print( session.getAttribute("height") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t      <tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td ><b>Weight :</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td  class=\"basicDetails\" contenteditable=\"false\">");
      out.print( session.getAttribute("weight") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t    <tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td ><b>Mother Tongue :</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td  class=\"basicDetails\" contenteditable=\"false\">");
      out.print( session.getAttribute("Mother_tongue") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t    <tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td ><b>Caste :</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td  class=\"basicDetails\" contenteditable=\"false\">");
      out.print( session.getAttribute("caste") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t    <tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td ><b>Annual Income :</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td  class=\"basicDetails\" contenteditable=\"false\">");
      out.print( session.getAttribute("Annual_Income") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t    <tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td ><b>Profile Managed by :</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td  class=\"basicDetails\" contenteditable=\"false\">");
      out.print( session.getAttribute("profilemanageby") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>  \r\n");
      out.write("    \t\t\t\t\t\t \r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t    \r\n");
      out.write("    \t\t\t\t    </tbody>                        \r\n");
      out.write("\t\t\t\t</table>   \r\n");
      out.write("\t\t\t\t                                      \r\n");
      out.write("                    </div>    \r\n");
      out.write("                                                                              \r\n");
      out.write("              </div>       \r\n");
      out.write("              \r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write("       <div class=\"col-lg-6 col-md-6 col-sm-12\">  <!-----middle profile detail------------------->    \r\n");
      out.write("           \r\n");
      out.write("              <div class=\"card\" >           <!----------About Me---------->\r\n");
      out.write("                      <div class=\"card-header\" style=\"margin-top: 5px;\">           \r\n");
      out.write("                         <p style=\"font-family: Agnes; font-size: 2em;\"><b>About Me</b></p> \r\n");
      out.write("                         <button class=\"btn-sm btn-primary\"> Edit</button>                 \r\n");
      out.write("                      </div>\r\n");
      out.write("                      \r\n");
      out.write("                      <div class=\"card-content\" style=\"margin-top: 5px;\">           \r\n");
      out.write("                    <table class=\"table\">\r\n");
      out.write("    \t\t        \t<tbody>\r\n");
      out.write("    \t\t        \t\t<p>I have completed my B.E in computers and currently i am working in pune in one of the reputed IT organization . My outlook towards life is modern but i am equally grounded with my traditions .My hobbies are dancing, shopping and travelling.</p>\t\t\t\t   \t\t\t\t\t\t                   \r\n");
      out.write("    \t\t\t\t\t  \t\t\t\t    \r\n");
      out.write("    \t\t\t\t    </tbody>                        \r\n");
      out.write("\t\t\t\t</table>                                         \r\n");
      out.write("                    </div>                                                              \r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("              <div class=\"card\" style=\"margin-top: -20px;\">           <!----------Education Carrer---------->\r\n");
      out.write("                      <div class=\"card-header\" style=\"margin-top: 5px;\">           \r\n");
      out.write("                         <p style=\"font-family: Agnes; font-size: 2em;\"><b>Education Carrer</b></p>  \r\n");
      out.write("                         <button class=\"btn-sm btn-primary\"> Edit</button>                \r\n");
      out.write("                    </div>\r\n");
      out.write("                      <div class=\"card-content\" style=\"margin-top: 5px;\">           \r\n");
      out.write("                    <table class=\"table\" >\r\n");
      out.write("    \t\t        \t<tbody>\r\n");
      out.write("    \t\t        \t\t<tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Highest Education :</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("education") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t    <tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td ><b>Occupation :</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td >");
      out.print( session.getAttribute("occupation") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t    \r\n");
      out.write("    \t\t\t\t\t   \r\n");
      out.write("    \t\t\t\t\t    \r\n");
      out.write("    \t\t\t\t    </tbody>\r\n");
      out.write("                        \r\n");
      out.write("\t\t\t\t</table>                                         \r\n");
      out.write("                    </div>                                                              \r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"card\" style=\"margin-top: -20px;\">           <!----------Life Style---------->\r\n");
      out.write("                      <div class=\"card-header\" style=\"margin-top: 5px;\">           \r\n");
      out.write("                         <p style=\"font-family: Agnes; font-size: 2em;\"><b>LifeStyle</b></p> \r\n");
      out.write("                         <button class=\"btn-sm btn-primary\"> Edit</button>                 \r\n");
      out.write("                    </div>\r\n");
      out.write("                      <div class=\"card-content\" style=\"margin-top: 5px;\">           \r\n");
      out.write("                    <table class=\"table\" >\r\n");
      out.write("    \t\t        \t<tbody>\r\n");
      out.write("    \t\t\t\t\t\t  <tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td ><b>Complexion :</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td >");
      out.print( session.getAttribute("complexion") );
      out.write("</td>\r\n");
      out.write("                                 <tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td ><b>Body Type :</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td >");
      out.print( session.getAttribute("body_type") );
      out.write("</td>\r\n");
      out.write("                                \r\n");
      out.write("    \t\t\t\t\t    <tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td ><b>Language Known :</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td >");
      out.print( session.getAttribute("language") );
      out.write("</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                <td ><b>Blood Group :</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td >");
      out.print( session.getAttribute("blood_group") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("       \t\t\t\t    </tbody>                        \r\n");
      out.write("\t\t\t\t</table>                                         \r\n");
      out.write("                    </div>                                                              \r\n");
      out.write("              </div>\r\n");
      out.write("               <div class=\"card\" style=\"margin-top: -5px;\">           <!----------Your Likes---------->\r\n");
      out.write("                      <div class=\"card-header\" style=\"margin-top: 5px;\">           \r\n");
      out.write("                         <p style=\"font-family: Agnes; font-size: 2em;\"><b>Family Details</b></p>\r\n");
      out.write("                         <button class=\"btn-sm btn-primary\"> Edit</button>                  \r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"card-content\" style=\"margin-top: 5px;\">           \r\n");
      out.write("                    <table class=\"table\" >\r\n");
      out.write("    \t\t        \t<tbody>\r\n");
      out.write("    \t\t        \t\t<tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Father's Name:</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("Fname") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t\t<tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Father's Occupation:</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("FOccupation") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t    <tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Mother's Name:</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("Mname") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t\t<tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Mother's Occupation:</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("MOccupation") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t\t<tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Brother(s):</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("Brothers") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t\t<tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Sister(s):</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("Sisters") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t\t<tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Uncle:</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("uncle") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t\t<tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Uncle(m):</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("unclem") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t\t<tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Aunt(s):</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("aunt") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("                            <tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Family Income:</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("FIncome") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("       \t\t\t\t    </tbody>                        \r\n");
      out.write("\t\t\t\t</table>                                         \r\n");
      out.write("                    </div>                                                              \r\n");
      out.write("              </div>\r\n");
      out.write("       \r\n");
      out.write("        \r\n");
      out.write("              <div class=\"card\" style=\"margin-top: -20px;\">           <!----------Life Style---------->\r\n");
      out.write("                      <div class=\"card-header\" style=\"margin-top: 5px;\">           \r\n");
      out.write("                         <p style=\"font-family: Agnes; font-size: 2em;\"><b>Astro Background</b></p>                  \r\n");
      out.write("                    \t<button class=\"btn-sm btn-primary\"> Edit</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                      <div class=\"card-content\" style=\"margin-top: 5px;\">           \r\n");
      out.write("                    <table class=\"table\" >\r\n");
      out.write("    \t\t        \t<tbody>\r\n");
      out.write("    \t\t\t\t\t\t  <tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td ><b>D.O.B :</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td >");
      out.print( session.getAttribute("DOB") );
      out.write("</td>\r\n");
      out.write("                                 <tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td ><b>Birth Time :</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td >");
      out.print( session.getAttribute("BirthTime") );
      out.write("</td>\r\n");
      out.write("                                \r\n");
      out.write("    \t\t\t\t\t    <tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td ><b>Birth Place :</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td >");
      out.print( session.getAttribute("BirthPlace") );
      out.write("</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                <td ><b>Rashi :</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td >");
      out.print( session.getAttribute("Rashi") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t\t  <tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td ><b>Nadi :</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td >");
      out.print( session.getAttribute("Nadi") );
      out.write("</td>\r\n");
      out.write("                                 <tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td ><b>Manglik :</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td >");
      out.print( session.getAttribute("Manglik") );
      out.write("</td>\r\n");
      out.write("                                \r\n");
      out.write("    \t\t\t\t\t    <tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td ><b>Gotra :</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td >");
      out.print( session.getAttribute("Gotra") );
      out.write("</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                <td ><b>Gaan :</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td >");
      out.print( session.getAttribute("Gaan") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t\t\t<tr>\r\n");
      out.write("    \t\t\t\t\t\t\t<td ><b>Devak :</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td >");
      out.print( session.getAttribute("Devak") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("       \t\t\t\t    </tbody>                        \r\n");
      out.write("\t\t\t\t</table>                                         \r\n");
      out.write("                    </div>                                                              \r\n");
      out.write("              </div>\r\n");
      out.write("         </div>    \r\n");
      out.write("         <div class=\"card\" style=\"margin-top: -5px;\">           <!----------Your Likes---------->\r\n");
      out.write("                      <div class=\"card-header\" style=\"margin-top: 5px;\">           \r\n");
      out.write("                         <p style=\"font-family: Agnes; font-size: 2em;\"><b>Partner References</b></p>\r\n");
      out.write("                         <button class=\"btn-sm btn-primary\"> Edit</button>                  \r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"card-content\" style=\"margin-top: 5px;\">           \r\n");
      out.write("                    <table class=\"table\" >\r\n");
      out.write("    \t\t        \t<tbody>\r\n");
      out.write("    \t\t        \t\t<tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Age:</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("PAge") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t\t<tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Marital Status:</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("PMaritalStatus") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t\t<tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Qualification:</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("PQualification") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t    <tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Job Specification:</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("PJobSpecification") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t\t<tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Complexion:</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("PComplexion") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t\t<tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Height:</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("PHeight") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t\t<tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Body Type:</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("PBodyType") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t\t<tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Diet:</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("PDiet") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t\t<tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Mother Tongue:</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("PMotherTongue") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t\t<tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Religion:</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("PReligion") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("                            <tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Caste:</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("PCaste") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t\t<tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Country Of Residence:</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("PCountryOfResidence") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t\t<tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>State:</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("PState") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\t\t\r\n");
      out.write("                            <tr >\r\n");
      out.write("    \t\t\t\t\t\t\t<td><b>Residence Status:</b></td>\r\n");
      out.write("    \t\t\t\t\t\t\t<td>");
      out.print( session.getAttribute("PResidenceStatus") );
      out.write("</td>\r\n");
      out.write("    \t\t\t\t\t\t</tr>\r\n");
      out.write("       \t\t\t\t    </tbody>                        \r\n");
      out.write("\t\t\t\t</table>                                         \r\n");
      out.write("                    </div>                                                              \r\n");
      out.write("              </div>\r\n");
      out.write("       \r\n");
      out.write("                            <!-------right profile------>\r\n");
      out.write("       <div class=\"col-lg-3 col-md-3 col-sm-12\">            <!-----------Simillar Profile---------------->\r\n");
      out.write("            <div class=\"card\" style=\"margin-top: 5px;\">\r\n");
      out.write("                    <div class=\"card-header\" style=\"margin-top: 5px;\">           \r\n");
      out.write("                         <p style=\"font-family: Agnes; font-size: 2em;\"><b>Similar Profile</b></p>  \r\n");
      out.write("                         <button class=\"btn-sm btn-primary\"> Edit</button>                \r\n");
      out.write("                      </div>           \r\n");
      out.write("                    <div class=\"card-content\">\r\n");
      out.write("                         <div class=\"flexslider\">\r\n");
      out.write("        \t\t\t\t\t <ul class=\"slides\">\r\n");
      out.write("                             <img width=\"100px\" alt=\"liam\" src=\"images/icon/p6.jpg\">\r\n");
      out.write("        \t\t\t\t\t\t<li data-thumb=\"images/icon/p1.jpg\">\r\n");
      out.write("        \t\t\t\t\t\t\t<img src=\"images/icon/a1.jpg\" />\r\n");
      out.write("        \t\t\t\t\t\t</li>\r\n");
      out.write("        \t\t\t\t\t\t<li data-thumb=\"images/icon/p2.jpg\">\r\n");
      out.write("        \t\t\t\t\t\t\t<img src=\"images/icon/p2.jpg\" />\r\n");
      out.write("        \t\t\t\t\t\t</li>\r\n");
      out.write("        \t\t\t\t\t\t<li data-thumb=\"images/icon/p3.jpg\">\r\n");
      out.write("        \t\t\t\t\t\t\t<img src=\"images/icon/p3.jpg\" />\r\n");
      out.write("        \t\t\t\t\t\t</li>\r\n");
      out.write("        \t\t\t\t\t\t<li data-thumb=\"images/icon/p4.jpg\">\r\n");
      out.write("        \t\t\t\t\t\t\t<img src=\"images/icon/p4.jpg\" />\r\n");
      out.write("        \t\t\t\t\t\t</li>\r\n");
      out.write("        \t\t\t\t\t </ul>\r\n");
      out.write("                          </div> \r\n");
      out.write("                     </div>                           \r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"card\" style=\"margin-top: 5px;\">   <!----------Daily Recomandation----------->\r\n");
      out.write("                    <div class=\"card-header\" style=\"margin-top: 5px;\">           \r\n");
      out.write("                         <p style=\"font-family: Agnes; font-size: 2em;\"><b>Daily Recommendation</b></p>                  \r\n");
      out.write("                      </div>           \r\n");
      out.write("                    <div class=\"card-content\">\r\n");
      out.write("                         <div class=\"flexslider\">\r\n");
      out.write("        \t\t\t\t\t <ul class=\"slides\">\r\n");
      out.write("                             <img width=\"100px\" alt=\"liam\" src=\"images/icon/p15.jpg\">\r\n");
      out.write("        \t\t\t\t\t\t<li data-thumb=\"images/icon/p1.jpg\">\r\n");
      out.write("        \t\t\t\t\t\t\t<img src=\"images/icon/a1.jpg\" />\r\n");
      out.write("        \t\t\t\t\t\t</li>\r\n");
      out.write("        \t\t\t\t\t\t<li data-thumb=\"images/icon/p2.jpg\">\r\n");
      out.write("        \t\t\t\t\t\t\t<img src=\"images/icon/p2.jpg\" />\r\n");
      out.write("        \t\t\t\t\t\t</li>\r\n");
      out.write("        \t\t\t\t\t\t<li data-thumb=\"images/icon/p3.jpg\">\r\n");
      out.write("        \t\t\t\t\t\t\t<img src=\"images/icon/p3.jpg\" />\r\n");
      out.write("        \t\t\t\t\t\t</li>\r\n");
      out.write("        \t\t\t\t\t\t<li data-thumb=\"images/icon/p4.jpg\">\r\n");
      out.write("        \t\t\t\t\t\t\t<img src=\"images/icon/p4.jpg\" />\r\n");
      out.write("        \t\t\t\t\t\t</li>\r\n");
      out.write("        \t\t\t\t\t </ul>\r\n");
      out.write("                          </div> \r\n");
      out.write("                     </div>                                           \r\n");
      out.write("              </div>\r\n");
      out.write("       </div>                 \r\n");
      out.write("    </div>  \r\n");
      out.write("    \r\n");
      out.write("<div class=\"row\" style=\"margin-top:2px;\">\r\n");
      out.write("           <div class=\"footer\">\r\n");
      out.write("    \t<div class=\"container\">\r\n");
      out.write("    \t\t<div class=\"col-md-4 col_2\">\r\n");
      out.write("  \t\t<h4>About Us</h4>\r\n");
      out.write("    \t\t\t<p>\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.\"</p>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"col-md-2 col_2\">\r\n");
      out.write("    \t\t\t<h4>Help & Support</h4>\r\n");
      out.write("    \t\t\t<ul class=\"footer_links\">\r\n");
      out.write("    \t\t\t\t<li><a href=\"#\">24x7 Live help</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"about.jsp\">Contact us</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"#\">Feedback</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"faq.jsp\">FAQs</a></li>\r\n");
      out.write("    \t\t\t</ul>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"col-md-2 col_2\">\r\n");
      out.write("    \t\t\t<h4>Quick Links</h4>\r\n");
      out.write("    \t\t\t<ul class=\"footer_links\">\r\n");
      out.write("    \t\t\t\t<li><a href=\"privacy.jsp\">Privacy Policy</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"terms.jsp\">Terms and Conditions</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"services.jsp\">Services</a></li>\r\n");
      out.write("    \t\t\t</ul>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"col-md-2 col_2\">\r\n");
      out.write("    \t\t\t<h4>Social</h4>\r\n");
      out.write("    \t\t\t<ul class=\"footer_social\">\r\n");
      out.write("\t\t\t\t  <li><a href=\"www.facebook.com\"><i class=\"fa fa-facebook fa1\"> </i></a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"www.twitter.com\"><i class=\"fa fa-twitter fa1\"> </i></a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"www.gmail.com\"><i class=\"fa fa-google-plus fa1\"> </i></a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"www.youtube.com\"><i class=\"fa fa-youtube fa1\"> </i></a></li>\r\n");
      out.write("\t\t\t    </ul>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("    \t\t<div class=\"copy\">\r\n");
      out.write("\t\t      <p>Copyright ©  Marital . All Rights Reserved </p>\r\n");
      out.write("\t        </div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </div>\r\n");
      out.write(" </div>            \r\n");
      out.write("               \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
