/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-05-31 05:05:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class upgrade_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--------------------------------------------------------------------\r\n");
      out.write("----------------------------------------------------------------------\r\n");
      out.write("\r\n");
      out.write("                        Manobandhan Upgrade Page\r\n");
      out.write("            \r\n");
      out.write("-----------------------------------------------------------------------\r\n");
      out.write("----------------------------------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("  \r\n");
      out.write("  <title>Manobandhan</title>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"images/logo/Mano1.png\" type=\"image/x-icon\" />    \r\n");
      out.write("    <link href=\"css/temp.css\" rel=\"stylesheet\" type=\"text/css\"/>    \r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/home.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/font-awesome.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/bootstrap-3.1.1.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\"/>    \r\n");
      out.write("        <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"js/jquery.flexisel.js\"></script>\r\n");
      out.write("        <script src=\"js/bootstrap.min.js\"></script> \r\n");
      out.write("        <script src=\"js/login1.js\"></script>      \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write(".banner {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  \r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write(" \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".banner img {vertical-align: middle;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".banner .content {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  background: rgb(0, 0, 0); /* Fallback color */\r\n");
      out.write("  background: rgba(0, 0, 0, 0.5); /* Black background with 0.5 opacity */\r\n");
      out.write("  color: #f1f1f1;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  margin-bottom: 68px;\r\n");
      out.write("}\r\n");
      out.write(".profile-picture {\r\n");
      out.write("\tborder-radius: 100%;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\t-webkit-box-sizing: content-box;\r\n");
      out.write("  \t-moz-box-sizing: content-box;\r\n");
      out.write("  \tbox-sizing: content-box;\t\r\n");
      out.write("}\r\n");
      out.write("\t.small-profile-picture {\r\n");
      out.write("\t\tborder: 2px solid #50597b;\r\n");
      out.write("\t\twidth: 40px;\r\n");
      out.write("\t\theight: 40px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.big-profile-picture {\r\n");
      out.write("\t\tmargin: 0 auto;\t\t\r\n");
      out.write("\t\tborder: 5px solid #50597b;\r\n");
      out.write("\t\twidth: 150px;\r\n");
      out.write("\t\theight: 150px;\r\n");
      out.write("        \r\n");
      out.write("\t}\r\n");
      out.write("    \r\n");
      out.write(".nav-tabs > li > a, \r\n");
      out.write(".nav-tabs > li > a:hover, \r\n");
      out.write(".nav-tabs > li > a:focus, \r\n");
      out.write(".nav-tabs > li.active > a, \r\n");
      out.write(".nav-tabs > li.active > a:hover,\r\n");
      out.write(".nav-tabs > li.active > a:focus {\r\n");
      out.write("  border: none;\r\n");
      out.write("  border-radius: 0;\r\n");
      out.write("  background-color:#ffa417;\r\n");
      out.write("}    \r\n");
      out.write("</style>\r\n");
      out.write("<!-- Add fancyBox main JS and CSS files -->\r\n");
      out.write("<script src=\"js/jquery.magnific-popup.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link href=\"css/popup.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$('.popup-with-zoom-anim').magnificPopup({\r\n");
      out.write("\t\t\t\ttype: 'inline',\r\n");
      out.write("\t\t\t\tfixedContentPos: false,\r\n");
      out.write("\t\t\t\tfixedBgPos: true,\r\n");
      out.write("\t\t\t\toverflowY: 'auto',\r\n");
      out.write("\t\t\t\tcloseBtnInside: true,\r\n");
      out.write("\t\t\t\tpreloader: false,\r\n");
      out.write("\t\t\t\tmidClick: true,\r\n");
      out.write("\t\t\t\tremovalDelay: 300,\r\n");
      out.write("\t\t\t\tmainClass: 'my-mfp-zoom-in'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<!---------------------header,Menu----------------------------------------------------------->\r\n");
      out.write("         \r\n");
      out.write("<!---------------------------Content mid------------------------------------------------------->\r\n");
      out.write("               \r\n");
      out.write("<div class=\"grid_3\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("   <div class=\"breadcrumb1\">\r\n");
      out.write("     <ul>\r\n");
      out.write("        <a href=\"profile.jsp\"><i class=\"fa fa-home home_1\"></i></a>\r\n");
      out.write("        <span class=\"divider\">&nbsp;|&nbsp;</span>\r\n");
      out.write("        <li class=\"current-page\"><h3>Upgrade</h3></li>\r\n");
      out.write("     </ul>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"col-md-3 pricing-table\">\r\n");
      out.write("\t  <div class=\"pricing-table-grid\">\r\n");
      out.write("\t\t<h3><span class=\"dollar\">Rs.</span>1100<br><span class=\"month1\">1 Month</span></h3>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><span>Basic</span></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"fa fa-envelope-o icon_3\"></i>E-Mails (10)</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"fa fa-phone icon_3\"></i>Phone Number (20)</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"fa fa-video-camera icon_3\"></i>Video Call (5)</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"fa fa-eye icon_3\"></i>Express Interest</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"fa fa-user icon_3\"></i>Profile Highlight</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"fa fa-smile-o icon_3\"></i>View Profile</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"fa fa-lock icon_3\"></i>Protect Photo</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"fa fa-smile-o icon_3\"></i>Get SMS Alert</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<a class=\"popup-with-zoom-anim order-btn\" href=\"#small-dialog\">Sign Up</a>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div id=\"small-dialog\" class=\"mfp-hide\">\r\n");
      out.write("\t\t\t<div class=\"pop_up\">\r\n");
      out.write("\t\t\t \t<div class=\"payment-online-form-left\">\r\n");
      out.write("\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t<h4><span class=\"shipping\"> </span>Shipping</h4>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><input class=\"text-box-dark\" type=\"text\" value=\"Frist Name\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Frist Name';}\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><input class=\"text-box-dark\" type=\"text\" value=\"Last Name\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Last Name';}\"></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><input class=\"text-box-dark\" type=\"text\" value=\"Email\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Email';}\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><input class=\"text-box-dark\" type=\"text\" value=\"Company Name\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Company Name';}\"></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><input class=\"text-box-dark\" type=\"text\" value=\"Phone\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Phone';}\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><input class=\"text-box-dark\" type=\"text\" value=\"Address\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Address';}\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clear\"> </div>\r\n");
      out.write("\t\t\t\t\t<ul class=\"payment-type\">\r\n");
      out.write("\t\t\t\t\t\t<h4><span class=\"payment\"> </span> Payments</h4>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"col_checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"3\" class=\"css-checkbox1\" type=\"checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"3\" name=\"demo_lbl_1\" class=\"css-label1\"> </label>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"visa\" href=\"#\"> </a>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"col_checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"4\" class=\"css-checkbox2\" type=\"checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"4\" name=\"demo_lbl_2\" class=\"css-label2\"> </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"paypal\" href=\"#\"> </a>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><input class=\"text-box-dark\" type=\"text\" value=\"Card Number\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Card Number';}\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><input class=\"text-box-dark\" type=\"text\" value=\"Name on card\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Name on card';}\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><input class=\"text-box-light hasDatepicker\" type=\"text\" id=\"datepicker\" value=\"Expiration Date\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Expiration Date';}\"><em class=\"pay-date\"> </em></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><input class=\"text-box-dark\" type=\"text\" value=\"Security Code\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Security Code';}\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"payment-sendbtns\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><input type=\"reset\" value=\"Cancel\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><input type=\"submit\" value=\"Process order\"></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("  \t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"col-md-3 pricing-table\">\r\n");
      out.write("\t\t<div class=\"pricing-table-grid\">\r\n");
      out.write("\t\t  <h3><span class=\"dollar\">Rs.</span>2999<br><span class=\"month1\">3 Months</span></h3>\r\n");
      out.write("\t\t  <ul>\r\n");
      out.write("\t\t\t<li><span>Silver</span></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"fa fa-envelope-o icon_3\"></i>E-Mails (10)</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"fa fa-phone icon_3\"></i>Phone Number (20)</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"fa fa-video-camera icon_3\"></i>Video Call (5)</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"fa fa-eye icon_3\"></i>Express Interest</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"fa fa-user icon_3\"></i>Profile Highlight</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"fa fa-smile-o icon_3\"></i>View Profile</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"fa fa-lock icon_3\"></i>Protect Photo</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"fa fa-smile-o icon_3\"></i>Get SMS Alert</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t  <a class=\"popup-with-zoom-anim order-btn\" href=\"#small-dialog\">Sign Up</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"col-md-3 pricing-table\">\r\n");
      out.write("\t\t<div class=\"pricing-table-grid\">\r\n");
      out.write("\t\t\t<h3><span class=\"dollar\">Rs.</span>3999<br><span class=\"month1\">6 Months</span></h3>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><span>Gold</span></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-envelope-o icon_3\"></i>E-Mails (10)</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-phone icon_3\"></i>Phone Number (20)</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-video-camera icon_3\"></i>Video Call (5)</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-eye icon_3\"></i>Express Interest</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-user icon_3\"></i>Profile Highlight</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-smile-o icon_3\"></i>View Profile</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-lock icon_3\"></i>Protect Photo</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-smile-o icon_3\"></i>Get SMS Alert</a></li>\r\n");
      out.write("\t\t    </ul>\r\n");
      out.write("\t\t\t<a class=\"popup-with-zoom-anim order-btn\" href=\"#small-dialog\">Sign Up</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"col-md-3 pricing-table\">\r\n");
      out.write("\t\t<div class=\"pricing-table-grid\">\r\n");
      out.write("\t\t\t<h3><span class=\"dollar\">Rs.</span>4999<br><span class=\"month1\">10 Months</span></h3>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><span>Diamond</span></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-envelope-o icon_3\"></i>E-Mails (10)</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-phone icon_3\"></i>Phone Number (20)</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-video-camera icon_3\"></i>Video Call (5)</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-eye icon_3\"></i>Express Interest</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-user icon_3\"></i>Profile Highlight</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-smile-o icon_3\"></i>View Profile</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-lock icon_3\"></i>Protect Photo</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-smile-o icon_3\"></i>Get SMS Alert</a></li>\r\n");
      out.write("\t\t    </ul>\r\n");
      out.write("\t\t\t<a class=\"popup-with-zoom-anim order-btn\" href=\"#small-dialog\">Sign Up</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"clearfix\"> </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!----------------------------Content mid end------------------------------------------------------>\r\n");
      out.write("<hr />    \r\n");
      out.write("   <!---------------------Footer------------------------->\r\n");
      out.write("<div class=\"row\" style=\"margin-top:2px;\">\r\n");
      out.write("           <div class=\"footer\">\r\n");
      out.write("    \t<div class=\"container\">\r\n");
      out.write("    \t\t<div class=\"col-md-4 col_2\">\r\n");
      out.write("    \t\t\t<h4>About Us</h4>\r\n");
      out.write("    \t\t\t<p>\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.\"</p>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"col-md-2 col_2\">\r\n");
      out.write("    \t\t\t<h4>Help & Support</h4>\r\n");
      out.write("    \t\t\t<ul class=\"footer_links\">\r\n");
      out.write("    \t\t\t\t<li><a href=\"#\">24x7 Live help</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"about.jsp\">Contact us</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"#\">Feedback</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"faq.jsp\">FAQs</a></li>\r\n");
      out.write("    \t\t\t</ul>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"col-md-2 col_2\">\r\n");
      out.write("    \t\t\t<h4>Quick Links</h4>\r\n");
      out.write("    \t\t\t<ul class=\"footer_links\">\r\n");
      out.write("    \t\t\t\t<li><a href=\"privacy.jsp\">Privacy Policy</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"terms.jsp\">Terms and Conditions</a></li>\r\n");
      out.write("    \t\t\t\t<li><a href=\"services.jsp\">Services</a></li>\r\n");
      out.write("    \t\t\t</ul>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"col-md-2 col_2\">\r\n");
      out.write("    \t\t\t<h4>Social</h4>\r\n");
      out.write("    \t\t\t<ul class=\"footer_social\">\r\n");
      out.write("\t\t\t\t  <li><a href=\"www.facebook.com\"><i class=\"fa fa-facebook fa1\"> </i></a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"www.twitter.com\"><i class=\"fa fa-twitter fa1\"> </i></a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"www.gmail.com\"><i class=\"fa fa-google-plus fa1\"> </i></a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"www.youtube.com\"><i class=\"fa fa-youtube fa1\"> </i></a></li>\r\n");
      out.write("\t\t\t    </ul>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("    \t\t<div class=\"copy\">\r\n");
      out.write("\t\t      <p>Copyright Â©  Marital . All Rights Reserved </p>\r\n");
      out.write("\t        </div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </div>\r\n");
      out.write(" </div>    \r\n");
      out.write("        \r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("// function to limt the length\r\n");
      out.write("function maxLengthCheck(object)\r\n");
      out.write("  {\r\n");
      out.write("    if (object.value.length > object.maxLength)\r\n");
      out.write("      object.value = object.value.slice(0, object.maxLength);\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    $(\".dropdown\").hover(            \r\n");
      out.write("        function() {\r\n");
      out.write("            $('.dropdown-menu', this).stop( true, true ).slideDown(\"fast\");\r\n");
      out.write("            $(this).toggleClass('open');        \r\n");
      out.write("        },\r\n");
      out.write("        function() {\r\n");
      out.write("            $('.dropdown-menu', this).stop( true, true ).slideUp(\"fast\");\r\n");
      out.write("            $(this).toggleClass('open');       \r\n");
      out.write("        }\r\n");
      out.write("    );\r\n");
      out.write("});\r\n");
      out.write("  \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
